<?php
return array(
    'liaozhichao'  => '廖志超',
    'yangjinghong' => '杨景宏',
    'huangjianjun' => '黄建军',
    'chenhuiyun'   => '陈辉云',
    'caipeng'      => '蔡鹏',
    'linpenghui'   => '林鹏辉',
    'chenxiaojun'  => '陈晓君',
    'wuminze'      => '伍敏哲',
    'chenzhidong'  => '陈志东',
    'liyouxin'     => '李有欣',
    'luotian'      => '罗恬',
    'zhengpeiying' => '郑培英',
    'zhengwei'     => '郑伟',
    'liuzhiwei'    => '刘至伟',
    'linzuoteng'   => '林作腾',
    'wuqingyuan'   => '吴清源',
    'hezhiliang'   => '何志良',
    'wangbin'      => '王斌',
    'chenbowen'    => '陈博文',
    'wangpengyu'   => '王鹏余',
    'luoyunkun'    => '罗云坤',
    'wangyouwei'   => '王尤伟',
    'fansujuan'    => '范素娟',
    'yeyuli'       => '叶聿丽',
    'xunyuepeng'   => '寻悦鹏',
    'wuyinan'      => '吴毅男',
    'zoulixiao'    => '邹黎晓',
    'zhangzhenda'  => '张振达',
    'chenjunliang' => '陈俊良',
    'muzhiyouwanyunying' => '拇指游玩运营',
    'muzhiyouwan' => '拇指游玩',
    'caohuayunying' => '草花运营',
    'caohua' => '草花',
    'huanleyuan' => '欢乐园',
    'huanleyuan1' => '欢乐园1',
    'huanleyuan2' => '欢乐园2',
    'huanleyuan3' => '欢乐园3',
    'lulihua' => '卢里华',
    'lulihua01' => '卢里华01',
    'lulihuayy01' => '卢里华专服',
    'lulihuayy02' => '卢里华专服',
    'anfeng' => '安峰',
    'anfengios' => '安峰ios',
    'anfengkf' => '安峰KF',
    'anfengyy' => '安峰YY',
    'anfengyunying' => '安峰运营',
    'linyou' => '麟游',
    'shouyouhui' => '手游',
    'shouyouhui01' => '手游01',
    'shouyouhui02' => '手游02',
    'shouyouhui03' => '手游03',
    'kuaiwan01' => '快玩-混服',
    'kuaiwan02' => '快玩专服02',
    'kuaiwan03' => '快玩专服03',
    'kuaiwan04' => '快玩专服04',
    'jingyu01' => '鲸鱼混服',
    'anfenghaiwai' => '安峰海外专服',
    'anfenghaiwai02' => '安峰海外专服02',
    'kuaiyou01' => '快游专服01',
    'kuaiyou02' => '快游专服02',
    'kuaiyou03' => '快游专服03',
    'xiongmaowan' => '熊猫玩(混服)',
    'shoumeng' => '手盟专服',
    'yinhu' => '银狐专服',
    'kongzhongwang' => '空中网-霸道王爷',
    'qiangwandq' => '抢玩-三宫六院(专服)',
    'jingqi' => '鲸旗',
    'guaimaoyunying1' => '怪猫1',
    'guaimaoyunying2' => '怪猫2',
);





