<?php
//卡牌基础
return array (
  6001 => 
  array (
    'id' => 6001,
    'name' => '달빛의 연못',
    'picture' => 'card_pt_001',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6001,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6002 => 
  array (
    'id' => 6002,
    'name' => '호수의 정자',
    'picture' => 'card_pt_002',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 4,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6002,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6003 => 
  array (
    'id' => 6003,
    'name' => '희미한 등불',
    'picture' => 'card_pt_003',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 4,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6003,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6004 => 
  array (
    'id' => 6004,
    'name' => '봄날의 배꽃',
    'picture' => 'card_pt_004',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 4,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6004,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6005 => 
  array (
    'id' => 6005,
    'name' => '푸르른 정경',
    'picture' => 'card_pt_005',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6005,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6006 => 
  array (
    'id' => 6006,
    'name' => '군림천하',
    'picture' => 'card_pt_006',
    'quality' => 1,
    'ep1' => 1,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6006,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6007 => 
  array (
    'id' => 6007,
    'name' => '진실한 염원',
    'picture' => 'card_pt_007',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 1,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6007,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6008 => 
  array (
    'id' => 6008,
    'name' => '흐드러진 벚꽃',
    'picture' => 'card_pt_008',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 1,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6008,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6009 => 
  array (
    'id' => 6009,
    'name' => '희미한 달빛',
    'picture' => 'card_pt_009',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 1,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6009,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6010 => 
  array (
    'id' => 6010,
    'name' => '시가행렬',
    'picture' => 'card_pt_010',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6010,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6011 => 
  array (
    'id' => 6011,
    'name' => '번화한 도시',
    'picture' => 'card_pt_011',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 4,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6011,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6012 => 
  array (
    'id' => 6012,
    'name' => '물가의 잠자리',
    'picture' => 'card_pt_012',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 4,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6012,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6013 => 
  array (
    'id' => 6013,
    'name' => '별 헤는 밤',
    'picture' => 'card_pt_013',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 4,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6013,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6014 => 
  array (
    'id' => 6014,
    'name' => '청풍명월',
    'picture' => 'card_pt_014',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6014,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6015 => 
  array (
    'id' => 6015,
    'name' => '화려한 등불',
    'picture' => 'card_pt_015',
    'quality' => 1,
    'ep1' => 1,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6015,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6016 => 
  array (
    'id' => 6016,
    'name' => '웅장한 황좌',
    'picture' => 'card_pt_016',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 1,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6016,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6017 => 
  array (
    'id' => 6017,
    'name' => '봄날의 정원',
    'picture' => 'card_pt_017',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 1,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6017,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6018 => 
  array (
    'id' => 6018,
    'name' => '화창한 날씨',
    'picture' => 'card_pt_018',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 1,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6018,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6019 => 
  array (
    'id' => 6019,
    'name' => '백년해로',
    'picture' => 'card_pt_019',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6019,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6020 => 
  array (
    'id' => 6020,
    'name' => '푸른 정경',
    'picture' => 'card_pt_020',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 4,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6020,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6021 => 
  array (
    'id' => 6021,
    'name' => '따스한 정취',
    'picture' => 'card_pt_021',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 4,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6021,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6022 => 
  array (
    'id' => 6022,
    'name' => '장엄한 광경',
    'picture' => 'card_pt_022',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 4,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6022,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6023 => 
  array (
    'id' => 6023,
    'name' => '꽃내음',
    'picture' => 'card_pt_023',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6023,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6024 => 
  array (
    'id' => 6024,
    'name' => '조용하다',
    'picture' => 'card_pt_024',
    'quality' => 1,
    'ep1' => 1,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6024,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6025 => 
  array (
    'id' => 6025,
    'name' => '푸른 물결',
    'picture' => 'card_pt_025',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 1,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6025,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6026 => 
  array (
    'id' => 6026,
    'name' => '눈부신 햇살',
    'picture' => 'card_pt_026',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 1,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6026,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6027 => 
  array (
    'id' => 6027,
    'name' => '고귀한 봉황',
    'picture' => 'card_pt_027',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 1,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6027,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6028 => 
  array (
    'id' => 6028,
    'name' => '달빛의 물결',
    'picture' => 'card_pt_028',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6028,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6029 => 
  array (
    'id' => 6029,
    'name' => '새하얀 눈밭',
    'picture' => 'card_pt_029',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 4,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6029,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6030 => 
  array (
    'id' => 6030,
    'name' => '연꽃연못',
    'picture' => 'card_pt_030',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 4,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6030,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6031 => 
  array (
    'id' => 6031,
    'name' => '오솔길',
    'picture' => 'card_pt_031',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 4,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6031,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6032 => 
  array (
    'id' => 6032,
    'name' => '고풍적 정취',
    'picture' => 'card_pt_032',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6032,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6033 => 
  array (
    'id' => 6033,
    'name' => '난원의 누각',
    'picture' => 'card_pt_033',
    'quality' => 1,
    'ep1' => 1,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6033,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6034 => 
  array (
    'id' => 6034,
    'name' => '꽃길',
    'picture' => 'card_pt_034',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 1,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6034,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6035 => 
  array (
    'id' => 6035,
    'name' => '두전성이',
    'picture' => 'card_pt_035',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 1,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6035,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6036 => 
  array (
    'id' => 6036,
    'name' => '폐월수화',
    'picture' => 'card_pt_036',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 1,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6036,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6037 => 
  array (
    'id' => 6037,
    'name' => '화초만개',
    'picture' => 'card_pt_037',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6037,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6038 => 
  array (
    'id' => 6038,
    'name' => '아름다운 정경',
    'picture' => 'card_pt_038',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 4,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6038,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6039 => 
  array (
    'id' => 6039,
    'name' => '궁중연회',
    'picture' => 'card_pt_039',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 4,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6039,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6040 => 
  array (
    'id' => 6040,
    'name' => '꽃내음',
    'picture' => 'card_pt_040',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 4,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6040,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6041 => 
  array (
    'id' => 6041,
    'name' => '형형색색',
    'picture' => 'card_pt_041',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6041,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6042 => 
  array (
    'id' => 6042,
    'name' => '고요',
    'picture' => 'card_pt_042',
    'quality' => 1,
    'ep1' => 1,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6042,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6043 => 
  array (
    'id' => 6043,
    'name' => '푸른 소나무',
    'picture' => 'card_pt_043',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 1,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6043,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6044 => 
  array (
    'id' => 6044,
    'name' => '깊숙한 궁전',
    'picture' => 'card_pt_044',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 1,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6044,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6045 => 
  array (
    'id' => 6045,
    'name' => '붉은 등',
    'picture' => 'card_pt_045',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 1,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6045,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6046 => 
  array (
    'id' => 6046,
    'name' => '대나무',
    'picture' => 'card_pt_046',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6046,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6047 => 
  array (
    'id' => 6047,
    'name' => '호수의 풍경',
    'picture' => 'card_pt_047',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 4,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6047,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6048 => 
  array (
    'id' => 6048,
    'name' => '늦가을',
    'picture' => 'card_pt_048',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 4,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6048,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6049 => 
  array (
    'id' => 6049,
    'name' => '옥루',
    'picture' => 'card_pt_049',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 4,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6049,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6050 => 
  array (
    'id' => 6050,
    'name' => '백설',
    'picture' => 'card_pt_050',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6050,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6051 => 
  array (
    'id' => 6051,
    'name' => '붉은 담장',
    'picture' => 'card_pt_051',
    'quality' => 1,
    'ep1' => 1,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6051,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6052 => 
  array (
    'id' => 6052,
    'name' => '안개',
    'picture' => 'card_pt_052',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 1,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6052,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6053 => 
  array (
    'id' => 6053,
    'name' => '월하만남',
    'picture' => 'card_pt_053',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 1,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6053,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6054 => 
  array (
    'id' => 6054,
    'name' => '석양',
    'picture' => 'card_pt_054',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 1,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6054,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6055 => 
  array (
    'id' => 6055,
    'name' => '생생함',
    'picture' => 'card_pt_055',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6055,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6056 => 
  array (
    'id' => 6056,
    'name' => '촛불',
    'picture' => 'card_pt_056',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 4,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6056,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6057 => 
  array (
    'id' => 6057,
    'name' => '일출',
    'picture' => 'card_pt_057',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 4,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6057,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6058 => 
  array (
    'id' => 6058,
    'name' => '호수',
    'picture' => 'card_pt_058',
    'quality' => 1,
    'ep1' => 2,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 4,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6058,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6059 => 
  array (
    'id' => 6059,
    'name' => '분향기복',
    'picture' => 'card_pt_059',
    'quality' => 1,
    'ep1' => 4,
    'ep2' => 2,
    'ep3' => 2,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6059,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6060 => 
  array (
    'id' => 6060,
    'name' => '산과 바다',
    'picture' => 'card_pt_060',
    'quality' => 1,
    'ep1' => 1,
    'ep2' => 3,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6060,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  6061 => 
  array (
    'id' => 6061,
    'name' => '촛불주렴',
    'picture' => 'card_pt_061',
    'quality' => 1,
    'ep1' => 3,
    'ep2' => 1,
    'ep3' => 3,
    'ep4' => 3,
    'kind' => 99,
    'show' => '1|2',
    'item' => 6061,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7001 => 
  array (
    'id' => 7001,
    'name' => '심궁',
    'picture' => 'card_ff_001',
    'quality' => 2,
    'ep1' => 4,
    'ep2' => 8,
    'ep3' => 8,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7001,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7002 => 
  array (
    'id' => 7002,
    'name' => '하늘 별',
    'picture' => 'card_ff_002',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 2,
    'ep3' => 8,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7002,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7003 => 
  array (
    'id' => 7003,
    'name' => '청렴',
    'picture' => 'card_ff_003',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 8,
    'ep3' => 2,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7003,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7004 => 
  array (
    'id' => 7004,
    'name' => '귀안',
    'picture' => 'card_ff_004',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 8,
    'ep3' => 8,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7004,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7005 => 
  array (
    'id' => 7005,
    'name' => '봄기운',
    'picture' => 'card_ff_005',
    'quality' => 2,
    'ep1' => 13,
    'ep2' => 5,
    'ep3' => 5,
    'ep4' => 5,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7005,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7006 => 
  array (
    'id' => 7006,
    'name' => '봄소식',
    'picture' => 'card_ff_006',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 11,
    'ep3' => 5,
    'ep4' => 5,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7006,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7007 => 
  array (
    'id' => 7007,
    'name' => '꽃구경',
    'picture' => 'card_ff_007',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 5,
    'ep3' => 11,
    'ep4' => 5,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7007,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7008 => 
  array (
    'id' => 7008,
    'name' => '한여름의 꿈',
    'picture' => 'card_ff_008',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 5,
    'ep3' => 5,
    'ep4' => 11,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7008,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7009 => 
  array (
    'id' => 7009,
    'name' => '전쟁의 불길',
    'picture' => 'card_ff_009',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 7,
    'ep3' => 7,
    'ep4' => 7,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7009,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7010 => 
  array (
    'id' => 7010,
    'name' => '꾀꼬리',
    'picture' => 'card_ff_010',
    'quality' => 2,
    'ep1' => 4,
    'ep2' => 8,
    'ep3' => 8,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7010,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7011 => 
  array (
    'id' => 7011,
    'name' => '꿈속',
    'picture' => 'card_ff_011',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 2,
    'ep3' => 8,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7011,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7012 => 
  array (
    'id' => 7012,
    'name' => '정의',
    'picture' => 'card_ff_012',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 8,
    'ep3' => 2,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7012,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7013 => 
  array (
    'id' => 7013,
    'name' => '집권자',
    'picture' => 'card_ff_013',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 8,
    'ep3' => 8,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7013,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7014 => 
  array (
    'id' => 7014,
    'name' => '온정',
    'picture' => 'card_ff_014',
    'quality' => 2,
    'ep1' => 13,
    'ep2' => 5,
    'ep3' => 5,
    'ep4' => 5,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7014,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7015 => 
  array (
    'id' => 7015,
    'name' => '오만',
    'picture' => 'card_ff_015',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 11,
    'ep3' => 5,
    'ep4' => 5,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7015,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7016 => 
  array (
    'id' => 7016,
    'name' => '달밤궁전',
    'picture' => 'card_ff_016',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 5,
    'ep3' => 11,
    'ep4' => 5,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7016,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7017 => 
  array (
    'id' => 7017,
    'name' => '모의천하',
    'picture' => 'card_ff_017',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 5,
    'ep3' => 5,
    'ep4' => 11,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7017,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7018 => 
  array (
    'id' => 7018,
    'name' => '녹엽 흩날린다',
    'picture' => 'card_ff_018',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 7,
    'ep3' => 7,
    'ep4' => 7,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7018,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7019 => 
  array (
    'id' => 7019,
    'name' => '맞서 싸우다',
    'picture' => 'card_ff_019',
    'quality' => 2,
    'ep1' => 4,
    'ep2' => 8,
    'ep3' => 8,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7019,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7020 => 
  array (
    'id' => 7020,
    'name' => '사냥',
    'picture' => 'card_ff_020',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 2,
    'ep3' => 8,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7020,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7021 => 
  array (
    'id' => 7021,
    'name' => '우아함',
    'picture' => 'card_ff_021',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 8,
    'ep3' => 2,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7021,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7022 => 
  array (
    'id' => 7022,
    'name' => '군림천하',
    'picture' => 'card_ff_022',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 8,
    'ep3' => 8,
    'ep4' => 2,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7022,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7023 => 
  array (
    'id' => 7023,
    'name' => '구속',
    'picture' => 'card_ff_023',
    'quality' => 2,
    'ep1' => 13,
    'ep2' => 5,
    'ep3' => 5,
    'ep4' => 5,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7023,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7024 => 
  array (
    'id' => 7024,
    'name' => '정자',
    'picture' => 'card_ff_024',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 11,
    'ep3' => 5,
    'ep4' => 5,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7024,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7025 => 
  array (
    'id' => 7025,
    'name' => '음주',
    'picture' => 'card_ff_025',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 5,
    'ep3' => 11,
    'ep4' => 5,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7025,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7026 => 
  array (
    'id' => 7026,
    'name' => '대치',
    'picture' => 'card_ff_026',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 5,
    'ep3' => 5,
    'ep4' => 11,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7026,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7027 => 
  array (
    'id' => 7027,
    'name' => '기다림',
    'picture' => 'card_ff_027',
    'quality' => 2,
    'ep1' => 7,
    'ep2' => 7,
    'ep3' => 7,
    'ep4' => 7,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7027,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7028 => 
  array (
    'id' => 7028,
    'name' => '요청',
    'picture' => 'card_ff_028',
    'quality' => 2,
    'ep1' => 4,
    'ep2' => 8,
    'ep3' => 8,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7028,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  7029 => 
  array (
    'id' => 7029,
    'name' => '안귀',
    'picture' => 'card_ff_029',
    'quality' => 2,
    'ep1' => 10,
    'ep2' => 2,
    'ep3' => 8,
    'ep4' => 8,
    'kind' => 99,
    'show' => '1|2',
    'item' => 7029,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8001 => 
  array (
    'id' => 8001,
    'name' => '푸른 소나무',
    'picture' => 'card_xs_001',
    'quality' => 3,
    'ep1' => 21,
    'ep2' => 40,
    'ep3' => 20,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8001,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8002 => 
  array (
    'id' => 8002,
    'name' => '소청 집필',
    'picture' => 'card_xs_002',
    'quality' => 3,
    'ep1' => 25,
    'ep2' => 19,
    'ep3' => 38,
    'ep4' => 19,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8002,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8003 => 
  array (
    'id' => 8003,
    'name' => '백발백중',
    'picture' => 'card_xs_003',
    'quality' => 3,
    'ep1' => 41,
    'ep2' => 20,
    'ep3' => 20,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8003,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8004 => 
  array (
    'id' => 8004,
    'name' => '호적수',
    'picture' => 'card_xs_004',
    'quality' => 3,
    'ep1' => 41,
    'ep2' => 20,
    'ep3' => 20,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8004,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8005 => 
  array (
    'id' => 8005,
    'name' => '반하 개화',
    'picture' => 'card_xs_005',
    'quality' => 3,
    'ep1' => 41,
    'ep2' => 20,
    'ep3' => 20,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8005,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8006 => 
  array (
    'id' => 8006,
    'name' => '거문고',
    'picture' => 'card_xs_006',
    'quality' => 3,
    'ep1' => 31,
    'ep2' => 20,
    'ep3' => 30,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8006,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8007 => 
  array (
    'id' => 8007,
    'name' => '우산이 될게',
    'picture' => 'card_xs_007',
    'quality' => 3,
    'ep1' => 21,
    'ep2' => 40,
    'ep3' => 20,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8007,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8008 => 
  array (
    'id' => 8008,
    'name' => '꽃잎이 흩날림',
    'picture' => 'card_xs_008',
    'quality' => 3,
    'ep1' => 29,
    'ep2' => 18,
    'ep3' => 36,
    'ep4' => 18,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8008,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8009 => 
  array (
    'id' => 8009,
    'name' => '가을색',
    'picture' => 'card_xs_009',
    'quality' => 3,
    'ep1' => 21,
    'ep2' => 20,
    'ep3' => 40,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8009,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8010 => 
  array (
    'id' => 8010,
    'name' => '북소리',
    'picture' => 'card_xs_010',
    'quality' => 3,
    'ep1' => 41,
    'ep2' => 40,
    'ep3' => 10,
    'ep4' => 10,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8010,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8011 => 
  array (
    'id' => 8011,
    'name' => '깊은 밤',
    'picture' => 'card_xs_011',
    'quality' => 3,
    'ep1' => 27,
    'ep2' => 36,
    'ep3' => 18,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8011,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8012 => 
  array (
    'id' => 8012,
    'name' => '설태매골',
    'picture' => 'card_xs_012',
    'quality' => 3,
    'ep1' => 41,
    'ep2' => 10,
    'ep3' => 40,
    'ep4' => 10,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8012,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8013 => 
  array (
    'id' => 8013,
    'name' => '대나무의 정',
    'picture' => 'card_xs_013',
    'quality' => 3,
    'ep1' => 21,
    'ep2' => 20,
    'ep3' => 20,
    'ep4' => 40,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8013,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8014 => 
  array (
    'id' => 8014,
    'name' => '거문고 소리',
    'picture' => 'card_xs_014',
    'quality' => 3,
    'ep1' => 45,
    'ep2' => 18,
    'ep3' => 18,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8014,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8015 => 
  array (
    'id' => 8015,
    'name' => '가면',
    'picture' => 'card_xs_015',
    'quality' => 3,
    'ep1' => 47,
    'ep2' => 9,
    'ep3' => 9,
    'ep4' => 36,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8015,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8016 => 
  array (
    'id' => 8016,
    'name' => '쓸쓸함',
    'picture' => 'card_xs_016',
    'quality' => 3,
    'ep1' => 11,
    'ep2' => 10,
    'ep3' => 40,
    'ep4' => 40,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8016,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8017 => 
  array (
    'id' => 8017,
    'name' => '갓 핀 연꽃',
    'picture' => 'card_xs_017',
    'quality' => 3,
    'ep1' => 35,
    'ep2' => 22,
    'ep3' => 22,
    'ep4' => 22,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8017,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8018 => 
  array (
    'id' => 8018,
    'name' => '환상',
    'picture' => 'card_xs_018',
    'quality' => 3,
    'ep1' => 26,
    'ep2' => 25,
    'ep3' => 25,
    'ep4' => 25,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8018,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8019 => 
  array (
    'id' => 8019,
    'name' => '검은 구름',
    'picture' => 'card_xs_019',
    'quality' => 3,
    'ep1' => 44,
    'ep2' => 19,
    'ep3' => 19,
    'ep4' => 19,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8019,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8020 => 
  array (
    'id' => 8020,
    'name' => '화조풍월',
    'picture' => 'card_xs_020',
    'quality' => 3,
    'ep1' => 43,
    'ep2' => 19,
    'ep3' => 19,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8020,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8021 => 
  array (
    'id' => 8021,
    'name' => '눈이 흩날려',
    'picture' => 'card_xs_021',
    'quality' => 3,
    'ep1' => 21,
    'ep2' => 20,
    'ep3' => 40,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8021,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8022 => 
  array (
    'id' => 8022,
    'name' => '비가 내려',
    'picture' => 'card_xs_022',
    'quality' => 3,
    'ep1' => 47,
    'ep2' => 18,
    'ep3' => 18,
    'ep4' => 18,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8022,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8023 => 
  array (
    'id' => 8023,
    'name' => '꽃이 펴',
    'picture' => 'card_xs_023',
    'quality' => 3,
    'ep1' => 21,
    'ep2' => 40,
    'ep3' => 20,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8023,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  8024 => 
  array (
    'id' => 8024,
    'name' => '햇살을 안다',
    'picture' => 'card_xs_024',
    'quality' => 3,
    'ep1' => 27,
    'ep2' => 18,
    'ep3' => 36,
    'ep4' => 20,
    'kind' => 99,
    'show' => '1|2',
    'item' => 8024,
    'starstoryid' => NULL,
    'storyname' => NULL,
    'clothe' => NULL,
    'use' => 106,
    'clotheunlockstar' => NULL,
  ),
  9001 => 
  array (
    'id' => 9001,
    'name' => '운명의 열쇠',
    'picture' => 'card_tc_003',
    'quality' => 4,
    'ep1' => 384,
    'ep2' => 0,
    'ep3' => 66,
    'ep4' => 0,
    'kind' => 99,
    'show' => NULL,
    'item' => 9001,
    'starstoryid' => '15_1_1001|15_1_2001|15_1_3001|15_1_4001|15_1_5001|15_1_6001',
    'storyname' => '아는 사이-0|아는 사이-1|아는 사이-2|아는 사이-3|아는 사이-4|아는 사이-5',
    'clothe' => 
    array (
      'itemid' => 5,
      'num' => 1,
      'kind' => 111,
    ),
    'use' => 106,
    'clotheunlockstar' => 3,
  ),
  9002 => 
  array (
    'id' => 9002,
    'name' => '상처',
    'picture' => 'card_tc_002',
    'quality' => 4,
    'ep1' => 120,
    'ep2' => 120,
    'ep3' => 120,
    'ep4' => 120,
    'kind' => 99,
    'show' => 2,
    'item' => 9002,
    'starstoryid' => '10_1_1001|10_1_2001|10_1_3001|10_1_4001|10_1_5001|10_1_6001',
    'storyname' => '당신의 묘약-0|당신의 묘약-1|당신의 묘약-2|당신의 묘약-3|당신의 묘약-4|당신의 묘약-5',
    'clothe' => 
    array (
      'itemid' => 6,
      'num' => 1,
      'kind' => 111,
    ),
    'use' => 106,
    'clotheunlockstar' => 3,
  ),
);