<?php
//寻访-事件（客户端）
return array (
  10000 => 
  array (
    'id' => 10000,
    'type' => 5,
    'object' => 40,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '管事姑姑派你去取绸缎，必须速去速回。绸缎拿到了便快回宫吧。',
    'beizhu' => '大阿哥',
    'beizhu ' => 442,
  ),
  10010 => 
  array (
    'id' => 10010,
    'type' => 5,
    'object' => 130,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '你奉命出宫采购食材，马上雇车启程吧。事情办完后速速回宫。',
    'beizhu' => '宋玉',
    'beizhu ' => NULL,
  ),
  10020 => 
  array (
    'id' => 10020,
    'type' => 5,
    'object' => 180,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '你需速速出宫挑选近日宫廷盛宴所需食材。但你目前身份尚低，尚且不可随意走动，食材准备完毕就先回宫吧。',
    'beizhu' => '三阿哥',
    'beizhu ' => NULL,
  ),
  10030 => 
  array (
    'id' => 10030,
    'type' => 5,
    'object' => 250,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '你奉命取回容妃娘娘的首饰，可得小心！取完尽快送回宫，千万别弄丢了！',
    'beizhu' => '五阿哥',
    'beizhu ' => NULL,
  ),
  10040 => 
  array (
    'id' => 10040,
    'type' => 5,
    'object' => 280,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 2,
    'group' => 0,
    'text' => '你难得可以借外出采买宫中用品多少逛一番，但买完可得尽快回宫。',
    'beizhu' => '苏培盛',
    'beizhu ' => NULL,
  ),
  10050 => 
  array (
    'id' => 10050,
    'type' => 5,
    'object' => 350,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 3,
    'group' => 0,
    'text' => '你日渐消瘦，苏培盛看不过去，便借口拉你出宫散心。',
    'beizhu' => '十三阿哥',
    'beizhu ' => NULL,
  ),
  10060 => 
  array (
    'id' => 10060,
    'type' => 5,
    'object' => 440,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 2,
    'group' => 0,
    'text' => '宜妃宫里吃穿用度快没了，你得赶紧出宫提前备着。',
    'beizhu' => '夏国相',
    'beizhu ' => NULL,
  ),
  10070 => 
  array (
    'id' => 10070,
    'type' => 5,
    'object' => 460,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 3,
    'group' => 0,
    'text' => '烦心事太多，你借机告假，出宫散心。但你目前身份尚低，且不可随意走动，还是早些回宫为佳。',
    'beizhu' => '四阿哥',
    'beizhu ' => NULL,
  ),
  10080 => 
  array (
    'id' => 10080,
    'type' => 5,
    'object' => 480,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 4,
    'group' => 0,
    'text' => '家中无趣，你约了剪秋，两人偷溜出城。',
    'beizhu' => '岳兴阿',
    'beizhu ' => NULL,
  ),
  10180 => 
  array (
    'id' => 10180,
    'type' => 5,
    'object' => 500,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 4,
    'group' => 0,
    'text' => '家事纷繁，你不愿深陷其中，便独自一人出城散心。',
    'beizhu' => '太子',
    'beizhu ' => NULL,
  ),
  10130 => 
  array (
    'id' => 10130,
    'type' => 5,
    'object' => 530,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 0,
    'text' => '日子无趣，你想了想，便拉上苏培灵出城游玩。',
    'beizhu' => '敦郡王',
    'beizhu ' => NULL,
  ),
  10120 => 
  array (
    'id' => 10120,
    'type' => 5,
    'object' => 560,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 0,
    'text' => '有人擅闯城门，不能姑息，赶紧出城追回来！',
    'beizhu' => '恂亲王',
    'beizhu ' => NULL,
  ),
  10140 => 
  array (
    'id' => 10140,
    'type' => 5,
    'object' => 580,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 0,
    'text' => '你出城采草药，却和他人擦撞',
    'beizhu' => '固山贝子',
    'beizhu ' => NULL,
  ),
  10150 => 
  array (
    'id' => 10150,
    'type' => 5,
    'object' => 610,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 0,
    'text' => '疫情已了，天朗气清，你便想着出城看看。',
    'beizhu' => '廉亲王',
    'beizhu ' => NULL,
  ),
  20070 => 
  array (
    'id' => 20070,
    'type' => 5,
    'object' => 640,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 8,
    'group' => 0,
    'text' => '苏培灵被传病重，你着急出城去看望！',
    'beizhu' => '苏培灵',
    'beizhu ' => NULL,
  ),
  20080 => 
  array (
    'id' => 20080,
    'type' => 5,
    'object' => 660,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 0,
    'text' => '眼看就可下榻休息了，却有歹人将你掳出城！',
    'beizhu' => '万云龙',
    'beizhu ' => NULL,
  ),
  20290 => 
  array (
    'id' => 20290,
    'type' => 6,
    'object' => 39,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 17,
    'group' => 0,
    'text' => '纳兰明珠想介绍人给你认识',
    'beizhu' => '南怡秋',
    'beizhu ' => NULL,
  ),
  20300 => 
  array (
    'id' => 20300,
    'type' => 6,
    'object' => 40,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 0,
    'text' => '和珅要介绍自己的族妹给你认识',
    'beizhu' => '凌玉环',
    'beizhu ' => NULL,
  ),
  20310 => 
  array (
    'id' => 20310,
    'type' => 6,
    'object' => 42,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 1000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '太子妃派人传话，邀你前往潭拓寺一叙',
    'beizhu' => '太子妃',
    'beizhu ' => NULL,
  ),
  20320 => 
  array (
    'id' => 20320,
    'type' => 6,
    'object' => 37,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 0,
    'text' => '自从河南一别，睿亲王对你的评价日益上升',
    'beizhu' => '睿亲王',
    'beizhu ' => NULL,
  ),
  20330 => 
  array (
    'id' => 20330,
    'type' => 6,
    'object' => 43,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 1500,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 8,
    'group' => 0,
    'text' => '你在关外的事情已了，索菲娅特意前来给你送行',
    'beizhu' => '索菲娅',
    'beizhu ' => NULL,
  ),
  20331 => 
  array (
    'id' => 20331,
    'type' => 6,
    'object' => 33,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 2,
    'group' => 0,
    'text' => '街上偶遇，意外欠了礼亲王一个人情',
    'beizhu' => '礼亲王',
    'beizhu ' => NULL,
  ),
  20332 => 
  array (
    'id' => 20332,
    'type' => 7,
    'object' => 27,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 0,
    'text' => '一夜的相遇，令你和廉亲王的关系，更加的说不清道不明了',
    'beizhu' => '廉亲王',
    'beizhu ' => NULL,
  ),
  20333 => 
  array (
    'id' => 20333,
    'type' => 7,
    'object' => 12,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '阖宫上下都因太子急得不可开交，你也遍寻无果',
    'beizhu' => '皇太子',
    'beizhu ' => NULL,
  ),
  20334 => 
  array (
    'id' => 20334,
    'type' => 7,
    'object' => 14,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 4,
    'group' => 0,
    'text' => '固山贝子所辖的码头遭遇麻烦，他希望同你合作解决',
    'beizhu' => '固山贝子',
    'beizhu ' => NULL,
  ),
  20335 => 
  array (
    'id' => 20335,
    'type' => 7,
    'object' => 19,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 11,
    'group' => 0,
    'text' => '释白莲向你发来求助的信函，你决然前往',
    'beizhu' => '释白莲',
    'beizhu ' => NULL,
  ),
  20340 => 
  array (
    'id' => 20340,
    'type' => 6,
    'object' => 46,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '你与恂郡王弈棋时巧遇从云南归来的淳亲王',
    'beizhu' => '淳亲王',
    'beizhu ' => NULL,
  ),
  20341 => 
  array (
    'id' => 20341,
    'type' => 7,
    'object' => 46,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 15,
    'group' => 0,
    'text' => '你单独探望淳亲王，他向你表露自己的真实心迹',
    'beizhu' => '淳亲王',
    'beizhu ' => NULL,
  ),
  20400 => 
  array (
    'id' => 20400,
    'type' => 7,
    'object' => 53,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 16,
    'group' => 0,
    'text' => '你在酒楼与定南王会面，他提出了自己的条件',
    'beizhu' => '定南王',
    'beizhu ' => NULL,
  ),
  20410 => 
  array (
    'id' => 20410,
    'type' => 7,
    'object' => 54,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 12,
    'group' => 0,
    'text' => '靖南王带着礼物登门拜访，向你表明他的忠心',
    'beizhu' => '靖南王',
    'beizhu ' => NULL,
  ),
  20420 => 
  array (
    'id' => 20420,
    'type' => 7,
    'object' => 55,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 14,
    'group' => 0,
    'text' => '平南王在府邸准备酒菜招待你，告诉你他的想法',
    'beizhu' => '平南王',
    'beizhu ' => NULL,
  ),
  20430 => 
  array (
    'id' => 20430,
    'type' => 7,
    'object' => 56,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 15,
    'group' => 0,
    'text' => '平西王主动约你见面，希望能和你联手',
    'beizhu' => '平西王',
    'beizhu ' => NULL,
  ),
  20500 => 
  array (
    'id' => 20500,
    'type' => 7,
    'object' => 9,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 5000,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '苏培盛出事你鼎力相助，苏培灵登门道谢，表露心声',
    'beizhu' => '苏培灵',
    'beizhu ' => NULL,
  ),
  11010 => 
  array (
    'id' => 11010,
    'type' => 6,
    'object' => 20,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 15,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '吴三桂',
    'beizhu ' => NULL,
  ),
  11020 => 
  array (
    'id' => 11020,
    'type' => 6,
    'object' => 21,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 12,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '洪承畴',
    'beizhu ' => NULL,
  ),
  11030 => 
  array (
    'id' => 11030,
    'type' => 6,
    'object' => 22,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '范文程',
    'beizhu ' => NULL,
  ),
  11040 => 
  array (
    'id' => 11040,
    'type' => 6,
    'object' => 23,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 3,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '蒲松龄',
    'beizhu ' => NULL,
  ),
  11050 => 
  array (
    'id' => 11050,
    'type' => 6,
    'object' => 24,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 10,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '冯子材',
    'beizhu ' => NULL,
  ),
  11060 => 
  array (
    'id' => 11060,
    'type' => 6,
    'object' => 25,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 8,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '左宗棠',
    'beizhu ' => NULL,
  ),
  11070 => 
  array (
    'id' => 11070,
    'type' => 6,
    'object' => 26,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 14,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '林则徐',
    'beizhu ' => NULL,
  ),
  11080 => 
  array (
    'id' => 11080,
    'type' => 6,
    'object' => 27,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 4,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '金圣叹',
    'beizhu ' => NULL,
  ),
  11090 => 
  array (
    'id' => 11090,
    'type' => 6,
    'object' => 28,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 18,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '年羹尧',
    'beizhu ' => NULL,
  ),
  11100 => 
  array (
    'id' => 11100,
    'type' => 6,
    'object' => 29,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 11,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '曾国藩',
    'beizhu ' => NULL,
  ),
  11110 => 
  array (
    'id' => 11110,
    'type' => 6,
    'object' => 30,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 8,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '李鸿章',
    'beizhu ' => NULL,
  ),
  11120 => 
  array (
    'id' => 11120,
    'type' => 6,
    'object' => 31,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 3,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '郑板桥',
    'beizhu ' => NULL,
  ),
  11130 => 
  array (
    'id' => 11130,
    'type' => 6,
    'object' => 32,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 8,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '鳌拜',
    'beizhu ' => NULL,
  ),
  11016 => 
  array (
    'id' => 11016,
    'type' => 6,
    'object' => 99,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '胤祄',
    'beizhu ' => NULL,
  ),
  11017 => 
  array (
    'id' => 11017,
    'type' => 6,
    'object' => 44,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '胤礼',
    'beizhu ' => NULL,
  ),
  11018 => 
  array (
    'id' => 11018,
    'type' => 6,
    'object' => 45,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 0,
    'text' => '庄亲王得知你要挑选舞女，主动请缨前来帮忙',
    'beizhu' => '胤禄',
    'beizhu ' => NULL,
  ),
  11000 => 
  array (
    'id' => 11000,
    'type' => 6,
    'object' => 19,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 0,
    'text' => NULL,
    'beizhu' => '弘历',
    'beizhu ' => NULL,
  ),
  11001 => 
  array (
    'id' => 11001,
    'type' => 6,
    'object' => 10,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 10,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 0,
    'text' => '直郡王得知宋玉赠予了你一件宝物，他决定也要送你一件',
    'beizhu' => '大阿哥',
    'beizhu ' => NULL,
  ),
  12000 => 
  array (
    'id' => 12000,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12010 => 
  array (
    'id' => 12010,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12020 => 
  array (
    'id' => 12020,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12030 => 
  array (
    'id' => 12030,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12040 => 
  array (
    'id' => 12040,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12050 => 
  array (
    'id' => 12050,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12060 => 
  array (
    'id' => 12060,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12070 => 
  array (
    'id' => 12070,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12080 => 
  array (
    'id' => 12080,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12090 => 
  array (
    'id' => 12090,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12100 => 
  array (
    'id' => 12100,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12110 => 
  array (
    'id' => 12110,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12120 => 
  array (
    'id' => 12120,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12130 => 
  array (
    'id' => 12130,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12140 => 
  array (
    'id' => 12140,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12150 => 
  array (
    'id' => 12150,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12160 => 
  array (
    'id' => 12160,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12170 => 
  array (
    'id' => 12170,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12180 => 
  array (
    'id' => 12180,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  12190 => 
  array (
    'id' => 12190,
    'type' => NULL,
    'object' => NULL,
    'prob' => NULL,
    'shili' => NULL,
    'jibang' => NULL,
    'qiyun' => NULL,
    'ep' => NULL,
    'locale' => NULL,
    'group' => NULL,
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  100 => 
  array (
    'id' => 100,
    'type' => 4,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 2,
    'group' => 'xunfang_1010',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  150 => 
  array (
    'id' => 150,
    'type' => 2,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_1510',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  200 => 
  array (
    'id' => 200,
    'type' => 4,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_2006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  220 => 
  array (
    'id' => 220,
    'type' => 1,
    'object' => 17,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 10,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 3,
    'group' => 'xunfang_2206',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  250 => 
  array (
    'id' => 250,
    'type' => 2,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_2506',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  300 => 
  array (
    'id' => 300,
    'type' => 4,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  320 => 
  array (
    'id' => 320,
    'type' => 1,
    'object' => 12,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 10,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_3206',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  350 => 
  array (
    'id' => 350,
    'type' => 2,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_3506',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  400 => 
  array (
    'id' => 400,
    'type' => 4,
    'object' => 4,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_4009',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  420 => 
  array (
    'id' => 420,
    'type' => 1,
    'object' => 13,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 10,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 'xunfang_4209',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  450 => 
  array (
    'id' => 450,
    'type' => 2,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_4509',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  500 => 
  array (
    'id' => 500,
    'type' => 1,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_5008',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  600 => 
  array (
    'id' => 600,
    'type' => 2,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_6007',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  700 => 
  array (
    'id' => 700,
    'type' => 1,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_7006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  800 => 
  array (
    'id' => 800,
    'type' => 3,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_8007',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  900 => 
  array (
    'id' => 900,
    'type' => 3,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_9006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1000 => 
  array (
    'id' => 1000,
    'type' => 2,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_10010',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1100 => 
  array (
    'id' => 1100,
    'type' => 3,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 4,
    'group' => 'xunfang_11006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1110 => 
  array (
    'id' => 1110,
    'type' => 3,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 'xunfang_11106',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1120 => 
  array (
    'id' => 1120,
    'type' => 3,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 10,
    'group' => 'xunfang_11206',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1200 => 
  array (
    'id' => 1200,
    'type' => 4,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 2,
    'group' => 'xunfang_12006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1210 => 
  array (
    'id' => 1210,
    'type' => 4,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 3,
    'group' => 'xunfang_12006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1220 => 
  array (
    'id' => 1220,
    'type' => 4,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 'xunfang_12006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1230 => 
  array (
    'id' => 1230,
    'type' => 4,
    'object' => 4,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_12006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1300 => 
  array (
    'id' => 1300,
    'type' => 4,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_13006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1310 => 
  array (
    'id' => 1310,
    'type' => 4,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 16,
    'group' => 'xunfang_13006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1320 => 
  array (
    'id' => 1320,
    'type' => 4,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 17,
    'group' => 'xunfang_13006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1330 => 
  array (
    'id' => 1330,
    'type' => 4,
    'object' => 4,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 18,
    'group' => 'xunfang_13006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1400 => 
  array (
    'id' => 1400,
    'type' => 3,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 'xunfang_14006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1410 => 
  array (
    'id' => 1410,
    'type' => 3,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 2,
    'group' => 'xunfang_14006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1420 => 
  array (
    'id' => 1420,
    'type' => 3,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 4,
    'group' => 'xunfang_14006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1430 => 
  array (
    'id' => 1430,
    'type' => 4,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_14006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1440 => 
  array (
    'id' => 1440,
    'type' => 4,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 'xunfang_14006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1450 => 
  array (
    'id' => 1450,
    'type' => 4,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_14006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1460 => 
  array (
    'id' => 1460,
    'type' => 4,
    'object' => 4,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 14,
    'group' => 'xunfang_14006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1470 => 
  array (
    'id' => 1470,
    'type' => 1,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_14006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1500 => 
  array (
    'id' => 1500,
    'type' => 4,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 'xunfang_15006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1510 => 
  array (
    'id' => 1510,
    'type' => 4,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 3,
    'group' => 'xunfang_15006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1520 => 
  array (
    'id' => 1520,
    'type' => 4,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 'xunfang_15006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1530 => 
  array (
    'id' => 1530,
    'type' => 4,
    'object' => 4,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 'xunfang_15006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1600 => 
  array (
    'id' => 1600,
    'type' => 3,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 4,
    'group' => 'xunfang_16006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1610 => 
  array (
    'id' => 1610,
    'type' => 3,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 12,
    'group' => 'xunfang_16006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1620 => 
  array (
    'id' => 1620,
    'type' => 3,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 14,
    'group' => 'xunfang_16006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1700 => 
  array (
    'id' => 1700,
    'type' => 2,
    'object' => 0,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_17506',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1710 => 
  array (
    'id' => 1710,
    'type' => 4,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 15,
    'group' => 'xunfang_17006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1720 => 
  array (
    'id' => 1720,
    'type' => 4,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 16,
    'group' => 'xunfang_17006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1730 => 
  array (
    'id' => 1730,
    'type' => 4,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 17,
    'group' => 'xunfang_17006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1740 => 
  array (
    'id' => 1740,
    'type' => 4,
    'object' => 4,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 18,
    'group' => 'xunfang_17006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1800 => 
  array (
    'id' => 1800,
    'type' => 3,
    'object' => 1,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 12,
    'group' => 'xunfang_18006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1810 => 
  array (
    'id' => 1810,
    'type' => 3,
    'object' => 2,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 14,
    'group' => 'xunfang_18006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
  1820 => 
  array (
    'id' => 1820,
    'type' => 3,
    'object' => 3,
    'prob' => 1000,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 15,
    'group' => 'xunfang_18006',
    'text' => NULL,
    'beizhu' => NULL,
    'beizhu ' => NULL,
  ),
);