<?php
//特殊关卡
return array (
  20 => 
  array (
    'id' => 20,
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 1,
    'unlock' => 100,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  40 => 
  array (
    'id' => 40,
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 1,
    'unlock' => 300,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  50 => 
  array (
    'id' => 50,
    'type' => 1,
    'roleid' => 5,
    'unlocktype' => 1,
    'unlock' => 800,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  100 => 
  array (
    'id' => 100,
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 0,
    'unlock' => 0,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  110 => 
  array (
    'id' => 110,
    'type' => 1,
    'roleid' => 11,
    'unlocktype' => 3,
    'unlock' => 205,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  900 => 
  array (
    'id' => 900,
    'type' => 1,
    'roleid' => 9,
    'unlocktype' => 3,
    'unlock' => 253,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  1100 => 
  array (
    'id' => 1100,
    'type' => 2,
    'roleid' => 19,
    'unlocktype' => 1,
    'unlock' => 500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  1200 => 
  array (
    'id' => 1200,
    'type' => 1,
    'roleid' => 12,
    'unlocktype' => 1,
    'unlock' => 500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  1300 => 
  array (
    'id' => 1300,
    'type' => 1,
    'roleid' => 13,
    'unlocktype' => 1,
    'unlock' => 500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  1400 => 
  array (
    'id' => 1400,
    'type' => 1,
    'roleid' => 14,
    'unlocktype' => 1,
    'unlock' => 500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  1500 => 
  array (
    'id' => 1500,
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 1,
    'unlock' => 500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  1600 => 
  array (
    'id' => 1600,
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 3,
    'unlock' => 430,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  1700 => 
  array (
    'id' => 1700,
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 3,
    'unlock' => 470,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  1800 => 
  array (
    'id' => 1800,
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 1,
    'unlock' => 500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  1900 => 
  array (
    'id' => 1900,
    'type' => 2,
    'roleid' => 15,
    'unlocktype' => 1,
    'unlock' => 500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  2000 => 
  array (
    'id' => 2000,
    'type' => 2,
    'roleid' => 20,
    'unlocktype' => 1,
    'unlock' => 500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  2101 => 
  array (
    'id' => 2101,
    'type' => 2,
    'roleid' => 1,
    'unlocktype' => 3,
    'unlock' => 135,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  2201 => 
  array (
    'id' => 2201,
    'type' => 2,
    'roleid' => 2,
    'unlocktype' => 3,
    'unlock' => 210,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  2202 => 
  array (
    'id' => 2202,
    'type' => 2,
    'roleid' => 2,
    'unlocktype' => 3,
    'unlock' => 225,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  2301 => 
  array (
    'id' => 2301,
    'type' => 2,
    'roleid' => 3,
    'unlocktype' => 3,
    'unlock' => 285,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  2401 => 
  array (
    'id' => 2401,
    'type' => 2,
    'roleid' => 4,
    'unlocktype' => 3,
    'unlock' => 450,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  2501 => 
  array (
    'id' => 2501,
    'type' => 2,
    'roleid' => 5,
    'unlocktype' => 3,
    'unlock' => 482,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban1' => 
  array (
    'id' => 'jiban1',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 2,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban10' => 
  array (
    'id' => 'jiban10',
    'type' => 1,
    'roleid' => 13,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban11' => 
  array (
    'id' => 'jiban11',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban12' => 
  array (
    'id' => 'jiban12',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban13' => 
  array (
    'id' => 'jiban13',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban14' => 
  array (
    'id' => 'jiban14',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban15' => 
  array (
    'id' => 'jiban15',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 3,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban16' => 
  array (
    'id' => 'jiban16',
    'type' => 1,
    'roleid' => 13,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 4,
    'color' => 5,
    'voice' => 1,
    'tree' => 1,
  ),
  'jiban17' => 
  array (
    'id' => 'jiban17',
    'type' => 1,
    'roleid' => 14,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 2,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban18' => 
  array (
    'id' => 'jiban18',
    'type' => 1,
    'roleid' => 14,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban19' => 
  array (
    'id' => 'jiban19',
    'type' => 1,
    'roleid' => 14,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban2' => 
  array (
    'id' => 'jiban2',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban20' => 
  array (
    'id' => 'jiban20',
    'type' => 1,
    'roleid' => 14,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban21' => 
  array (
    'id' => 'jiban21',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban22' => 
  array (
    'id' => 'jiban22',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 3,
    'color' => 5,
    'voice' => 1,
    'tree' => 1,
  ),
  'jiban23' => 
  array (
    'id' => 'jiban23',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban27' => 
  array (
    'id' => 'jiban27',
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 1,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban28' => 
  array (
    'id' => 'jiban28',
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 1,
    'color' => 5,
    'voice' => 1,
    'tree' => 1,
  ),
  'jiban3' => 
  array (
    'id' => 'jiban3',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban30' => 
  array (
    'id' => 'jiban30',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 2,
    'color' => 5,
    'voice' => 1,
    'tree' => 1,
  ),
  'jiban31' => 
  array (
    'id' => 'jiban31',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban32' => 
  array (
    'id' => 'jiban32',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban34' => 
  array (
    'id' => 'jiban34',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban35' => 
  array (
    'id' => 'jiban35',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban36' => 
  array (
    'id' => 'jiban36',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban37' => 
  array (
    'id' => 'jiban37',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban38' => 
  array (
    'id' => 'jiban38',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban39' => 
  array (
    'id' => 'jiban39',
    'type' => 1,
    'roleid' => 13,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban4' => 
  array (
    'id' => 'jiban4',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban40' => 
  array (
    'id' => 'jiban40',
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban41' => 
  array (
    'id' => 'jiban41',
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 1,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban42' => 
  array (
    'id' => 'jiban42',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 3,
    'color' => 5,
    'voice' => 1,
    'tree' => 1,
  ),
  'jiban5' => 
  array (
    'id' => 'jiban5',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban6' => 
  array (
    'id' => 'jiban6',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban7' => 
  array (
    'id' => 'jiban7',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban8' => 
  array (
    'id' => 'jiban8',
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 1,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban9' => 
  array (
    'id' => 'jiban9',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban45' => 
  array (
    'id' => 'jiban45',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 2,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'jiban100' => 
  array (
    'id' => 'jiban100',
    'type' => 1,
    'roleid' => 45,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban101' => 
  array (
    'id' => 'jiban101',
    'type' => 1,
    'roleid' => 45,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban102' => 
  array (
    'id' => 'jiban102',
    'type' => 1,
    'roleid' => 45,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 1,
    'color' => 5,
    'voice' => 1,
    'tree' => 2,
  ),
  'jiban110' => 
  array (
    'id' => 'jiban110',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban111' => 
  array (
    'id' => 'jiban111',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 4,
    'specMsg' => 1,
    'color' => 6,
    'voice' => 1,
    'tree' => 2,
  ),
  'jiban112' => 
  array (
    'id' => 'jiban112',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 1,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban113' => 
  array (
    'id' => 'jiban113',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban114' => 
  array (
    'id' => 'jiban114',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 2,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban120' => 
  array (
    'id' => 'jiban120',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban121' => 
  array (
    'id' => 'jiban121',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 1,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban122' => 
  array (
    'id' => 'jiban122',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban123' => 
  array (
    'id' => 'jiban123',
    'type' => 1,
    'roleid' => 15,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 3,
    'color' => 5,
    'voice' => 1,
    'tree' => 2,
  ),
  'jiban130' => 
  array (
    'id' => 'jiban130',
    'type' => 1,
    'roleid' => 12,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 1,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban131' => 
  array (
    'id' => 'jiban131',
    'type' => 1,
    'roleid' => 12,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban132' => 
  array (
    'id' => 'jiban132',
    'type' => 1,
    'roleid' => 12,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban133' => 
  array (
    'id' => 'jiban133',
    'type' => 1,
    'roleid' => 12,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 1,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban140' => 
  array (
    'id' => 'jiban140',
    'type' => 1,
    'roleid' => 11,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 3,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban141' => 
  array (
    'id' => 'jiban141',
    'type' => 1,
    'roleid' => 11,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban142' => 
  array (
    'id' => 'jiban142',
    'type' => 1,
    'roleid' => 11,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 1,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban143' => 
  array (
    'id' => 'jiban143',
    'type' => 1,
    'roleid' => 11,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 4,
    'specMsg' => 1,
    'color' => 6,
    'voice' => 1,
    'tree' => 2,
  ),
  'jiban150' => 
  array (
    'id' => 'jiban150',
    'type' => 1,
    'roleid' => 13,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 2,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban151' => 
  array (
    'id' => 'jiban151',
    'type' => 1,
    'roleid' => 13,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 1,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban152' => 
  array (
    'id' => 'jiban152',
    'type' => 1,
    'roleid' => 13,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban153' => 
  array (
    'id' => 'jiban153',
    'type' => 1,
    'roleid' => 13,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 4,
    'color' => 5,
    'voice' => 1,
    'tree' => 2,
  ),
  'jiban160' => 
  array (
    'id' => 'jiban160',
    'type' => 1,
    'roleid' => 9,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 4,
    'color' => 5,
    'voice' => 1,
    'tree' => 2,
  ),
  'jiban161' => 
  array (
    'id' => 'jiban161',
    'type' => 1,
    'roleid' => 9,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban162' => 
  array (
    'id' => 'jiban162',
    'type' => 1,
    'roleid' => 9,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban163' => 
  array (
    'id' => 'jiban163',
    'type' => 1,
    'roleid' => 9,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 1,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban170' => 
  array (
    'id' => 'jiban170',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban171' => 
  array (
    'id' => 'jiban171',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban172' => 
  array (
    'id' => 'jiban172',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban173' => 
  array (
    'id' => 'jiban173',
    'type' => 1,
    'roleid' => 18,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 3,
    'color' => 5,
    'voice' => 1,
    'tree' => 2,
  ),
  'jiban180' => 
  array (
    'id' => 'jiban180',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 2,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban181' => 
  array (
    'id' => 'jiban181',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban182' => 
  array (
    'id' => 'jiban182',
    'type' => 1,
    'roleid' => 17,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban190' => 
  array (
    'id' => 'jiban190',
    'type' => 1,
    'roleid' => 14,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban191' => 
  array (
    'id' => 'jiban191',
    'type' => 1,
    'roleid' => 14,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban192' => 
  array (
    'id' => 'jiban192',
    'type' => 1,
    'roleid' => 14,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 2,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban200' => 
  array (
    'id' => 'jiban200',
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 1,
    'color' => 3,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban201' => 
  array (
    'id' => 'jiban201',
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 4,
    'specMsg' => 1,
    'color' => 6,
    'voice' => 1,
    'tree' => 2,
  ),
  'jiban202' => 
  array (
    'id' => 'jiban202',
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 5,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 2,
  ),
  'jiban103' => 
  array (
    'id' => 'jiban103',
    'type' => 1,
    'roleid' => 45,
    'unlocktype' => 6,
    'unlock' => 0,
    'star' => 4,
    'specMsg' => 1,
    'color' => 6,
    'voice' => 1,
    'tree' => 0,
  ),
  'jiban203' => 
  array (
    'id' => 'jiban203',
    'type' => 1,
    'roleid' => 16,
    'unlocktype' => 6,
    'unlock' => 0,
    'star' => 4,
    'specMsg' => 1,
    'color' => 6,
    'voice' => 1,
    'tree' => 0,
  ),
  'jiban204' => 
  array (
    'id' => 'jiban204',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 200,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban205' => 
  array (
    'id' => 'jiban205',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 600,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban206' => 
  array (
    'id' => 'jiban206',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 1200,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban207' => 
  array (
    'id' => 'jiban207',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 2000,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban208' => 
  array (
    'id' => 'jiban208',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 2800,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban209' => 
  array (
    'id' => 'jiban209',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 3600,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban210' => 
  array (
    'id' => 'jiban210',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 4500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban211' => 
  array (
    'id' => 'jiban211',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 5500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban212' => 
  array (
    'id' => 'jiban212',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 6000,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiban213' => 
  array (
    'id' => 'jiban213',
    'type' => 1,
    'roleid' => 10,
    'unlocktype' => 1,
    'unlock' => 6500,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
);