<?php
/**
 * 所有mark信息
 */
return array(
    'king'=>array(
        'title'=>'养成正式',
        'url'=>'king.coolnull.com',
    ),
    'lyjx'=>array(
        'title'=>'怪猫-我要做皇帝',
        'url'=>'lyjx.zhisnet.cn',
    ),
    'jpxl'=>array(
        'title'=>'欢乐园-极品县令',
        'url'=>'jpxl.zhisnet.cn',
    ),
    'jwdgr'=>array(
        'title'=>'老爷吉祥官方服',
        'url'=>'jwdgr.zhisnet.cn',
    ),
    'gjjpch'=>array(
        'title'=>'草花-官居几品',
        'url'=>'gjjpch.zhisnet.cn',
    ),
    'lyjx6kw'=>array(
        'title'=>'麟游-叫我大官人',
        'url'=>'lyjx6kw.zhisnet.cn',
    ),
    'lyjxios'=>array(
        'title'=>'老爷吉祥ios',
        'url'=>'lyjxios.zhisnet.cn',
    ),
    'gjypaf'=>array(
        'title'=>'安峰-官居一品',
        'url'=>'gjypaf.zhisnet.cn',
    ),
    'gjypmzyw'=>array(
        'title'=>'拇指游玩-官居一品',
        'url'=>'gjypmzyw.zhisnet.cn',
    ),
    'llhzf'=>array(
        'title'=>'卢里华转服',
        'url'=>'llhzf.commpad.cn',
    ),
    'jpwysyh'=>array(
        'title'=>'手游汇-极品王爷',
        'url'=>'jpwysyh.zhisnet.cn',
    ),
    'wsdqg'=>array(
        'title'=>'鲸鱼-我是大官人',
        'url'=>'wsdqg.zhisnet.cn',
    ),
    'lyjxky'=>array(
        'title'=>'快游-官居几品',
        'url'=>'lyjxky.zhisnet.cn',
    ),
    'ypdckw'=>array(
        'title'=>'快玩-一品大臣',
        'url'=>'ypdckw.commpad.cn',
    ),
    'grwyyh'=>array(
        'title'=>'银狐-官人我要',
        'url'=>'grwyyh.commpad.cn',
    ),
    'jpdlysm'=>array(
        'title'=>'手盟-极品大老爷',
        'url'=>'jpdlysm.commpad.cn',
    ),
    'grqnejq'=>array(
        'title'=>'鲸旗-官人去哪儿',
        'url'=>'grqnejq.commpad.cn',
    ),
    'bdwykzw'=>array(
        'title'=>'空中网-霸道王爷',
        'url'=>'bdwykzw.commpad.cn',
    ),
    'lzqdgft'=>array(
        'title'=>'老子去当官繁体',
        'url'=>'lzqdgft.commpad.cn',
    ),
    'gjypdmw'=>array(
        'title'=>'大魔王-官居一品',
        'url'=>'gjypdmw.commpad.cn',
    ),
);