<?php  return array (
    'cs' => array (
        'login' => '登入模块',
        'guide' => '新手引导模块',
        'user' => '用户模块',
        'hero' => '伙伴模块',
        'item' => '道具模块',
        'wife' => '知己模块',
        'school' => '书院模块',
        'son' => '徒弟模块',
        'ranking' => '排行榜膜拜',
        'laofang' => '牢房',
        'wordboss' => '副本世界BOSS',
        'fengxiandian' => '奉先殿',
        'chenghao' => '称号',
        'xunfang' => '寻访',
        'mail' => '邮件列表',
        'club' => '宫殿模块',
        'daily' => '每日任务',
        'chengjiu' => '成就',
        'qiandao' => '签到',
        'fuli' => '福利',
        'jiulou' => '酒楼',
        'shop' => '商城',
        'task' => '任务',
        'yamen' => '宫斗战',
        'order' => '充值',
        'huodong' => '活动',
        'chat' => '聊天模块',
        'recode' => '兑换码模块',
        'hunt' => '狩猎模块',
        'taofa' => '讨伐模块',
        'hanlin' => '翰林院',
        'silkroad' => '丝绸之路',
        'kuayamen' => '跨服宫斗',
        'friends' => '好友模块',
        'guozijian' => '国子监',
        'kitchen' => '御膳房',
        'boite' => '新版酒楼',
        'admin' => '后台操作',
        'treasure' => '珍宝阁',
        'scpoint' => '特殊剧情',
        'flower' => '御花园',
        'fuyue' => '赴约',
        'banchai' => '办差',
        'sevendays' => '七日庆典',
        'business' => '行商',
        'baowu' => '四海奇珍',
        'card' => '卡牌',
    ),
    'mail' => array (
        'getMail' => '获得邮件',
        'redMails' => '读取/领取邮件',
        'delMail' => '删除邮件',
        'delMails' => '批量删除邮件',
        'openMails' => '打开邮件',
    ),
    'daily' => array (
        'getrwd' => '领取档次奖励',
        'gettask' => '领取任务奖励',
    ),
    'task' => array (
        'taskdo' => '做主线任务',
    ),
    'huodong' => array (
        'hdList' => '生效活动列表',
        'hd201Info' => '元宝消耗信息',
        'hd201Rwd' => '元宝消耗领取奖励',
        'hd202Info' => '名声消耗信息',
        'hd202Rwd' => '名声消耗领取奖励',
        'hd203Info' => '阅历消耗信息',
        'hd203Rwd' => '阅历消耗领取奖励',
        'hd204Info' => '限时强化书卷消耗信息',
        'hd204Rwd' => '限时强化书卷消耗领取奖励',
        'hd205Info' => '知己好感涨幅信息',
        'hd205Rwd' => '知己好感涨幅领取奖励',
        'hd206Info' => '势力涨幅信息',
        'hd206Rwd' => '势力涨幅领取奖励',
        'hd207Info' => '处理日常次数信息',
        'hd207Rwd' => '处理日常次数领取奖励',
        'hd208Info' => '累计登录天数信息',
        'hd208Rwd' => '累计登录天数领取奖励',
        'hd209Info' => '宫斗分数涨幅信息',
        'hd209Rwd' => '宫斗分数涨幅领取奖励',
        'hd210Info' => '联姻次数信息',
        'hd210Rwd' => '联姻次数领取奖励',
        'hd211Info' => '书院学习信息',
        'hd211Rwd' => '书院学习领取奖励',
        'hd212Info' => '限时办理阅历差事次数信息',
        'hd212Rwd' => '限时办理阅历差事次数领取奖励',
        'hd213Info' => '限时办理银两差事次数信息',
        'hd213Rwd' => '限时办理银两差事次数领取奖励',
        'hd214Info' => '限时办理名声差事次数信息',
        'hd214Rwd' => '限时办理名声差事次数领取奖励',
        'hd215Info' => '击杀葛尔丹次数信息',
        'hd215Rwd' => '击杀葛尔丹次数领取奖励',
        'hd216Info' => '挑战书消耗信息',
        'hd216Rwd' => '挑战书消耗领取奖励',
        'hd217Info' => '惩戒犯人次数信息',
        'hd217Rwd' => '惩戒犯人次数领取奖励',
        'hd218Info' => '赈灾次数信息',
        'hd218Rwd' => '赈灾次数领取奖励',
        'hd219Info' => '体力丹消耗信息',
        'hd219Rwd' => '体力丹消耗领取奖励',
        'hd220Info' => '活力丹消耗信息',
        'hd220Rwd' => '活力丹消耗领取奖励',
        'hd221Info' => '限时能力值涨幅信息',
        'hd221Rwd' => '限时能力值涨幅领取奖励',
        'hd222Info' => '赴宴次数信息',
        'hd222Rwd' => '赴宴次数领取奖励',
        'hd223Info' => '宫殿副本伤害信息',
        'hd223Rwd' => '宫殿副本伤害领取奖励',
        'hd224Info' => '宫殿副本击杀（累计击杀僵尸）信息',
        'hd224Rwd' => '宫殿副本击杀（累计击杀僵尸）领取奖励',
        'hd225Info' => '酒楼积分涨幅信息',
        'hd225Rwd' => '酒楼积分涨幅领取奖励',
        'hd226Rwd' => '银币消耗领取奖励',
        'hd250Info' => '宫殿冲榜',
        'hd251Info' => '关卡冲榜',
        'hd251buy' =>  '关卡冲榜-购买礼包',
        'hd252Info' => '势力冲榜',
        'hd252buy' =>  '势力冲榜-购买礼包',
        'hd253Info' => '好感涨幅冲榜',
        'hd254Info' => '宫斗冲榜',
        'hd255Info' => '阅历冲榜',
        'hd256Info' => '酒楼冲榜',
        'hd257Info' => '名声冲榜',
        'hd258Info' => '魅力冲榜',
        'hd260Info' => '充值活动-每日充值',
        'hd260Rwd' => '充值活动-每日充值领取奖励',
        'hd261Info' => '充值活动-累计充值',
        'hd261Rwd' => '充值活动-累计充值领取奖励',
        'hd262Info' => '充值活动-累天充值',
        'hd262Rwd' => '充值活动-累天充值领取奖励',
        'hd270Info' => '四大奸臣',
        'hd270Rwd' => '四大奸臣领取奖励',
        'hd271Info' => '巾帼五虎',
        'hd271Rwd' => '巾帼五虎领取奖励',
        'hd272Info' => '巾帼女将',
        'hd272Rwd' => '巾帼女将领取奖励',
        'hd280Info' => '新官上任',
        'hd280buy' => '新官上任-商城购买',
        'hd280exchange' => '新官上任-积分兑换',
        'hd280play' => '新官上任-打',
        'hd280paihang' => '新官上任-排行和奖励',
        'hd280Rwd' => '新官上任-领取奖励',
        'hd281Info' => '重阳节活动',
        'hd281buy' => '重阳节活动-商城购买',
        'hd281exchange' => '重阳节活动-积分兑换',
        'hd281play' => '重阳节活动-打',
        'hd281paihang' => '重阳节活动-排行和奖励',
        'hd281Rwd' => '重阳节活动-领取奖励',
        'hd281getRwd' => '重阳节活动-领取每日充值档次',
        'hd282Info' => '惩戒来福',
        'hd282buy' => '惩戒来福-商城购买',
        'hd282exchange' => '惩戒来福-积分兑换',
        'hd282play' => '惩戒来福-打',
        'hd282paihang' => '惩戒来福-排行和奖励',
        'hd282Rwd' => '惩戒来福-领取奖励',
        'hd283Info' => '国庆狂欢活动',
        'hd283buy' => '国庆狂欢活动-商城购买',
        'hd283exchange' => '国庆狂欢活动-积分兑换',
        'hd283play' => '国庆狂欢活动-打',
        'hd283paihang' => '国庆狂欢活动-排行和奖励',
        'hd283Rwd' => '国庆狂欢活动-领取奖励',
        'hd284Info' => '感恩节活动',
        'hd284buy' => '感恩节活动-商城购买',
        'hd284exchange' => '感恩节活动-积分兑换',
        'hd284play' => '感恩节活动-打',
        'hd284paihang' => '感恩节活动-排行和奖励',
        'hd284Rwd' => '感恩节活动-领取奖励',
        'hd284getRwd' => '感恩节活动-领取每日充值档次',
        'hd285Info' => '双十一活动',
        'hd285buy' => '双十一活动-商城单品购买',
        'hd285buyGift' => '双十一活动-商城礼包购买',
        'hd285getRwd' => '双十一活动-领取每日充值档次',
        'hd287Get' => '七天签到活动-领取奖励',
        'hd6500Get' => '四十五天签到活动-领取奖励',
        'hd290Info' => '双12转盘 -- 基本信息',
        'hd290Yao' => '双12转盘  -- 摇奖',
        'hd290log' => '双12转盘  -- 日志',
        'hd290exchange' => '双12转盘  -- 兑换',
        'hd291Info' => '双旦 -- (二个活动)基本信息',
        'hd291Zadan' => '双旦-- 砸蛋',
        'hd291Set' => '双旦 -- 单抽消费提示',
        'hd292exchange' => '双旦-搜集 兑换',
        'hd293Info' => '寻宝大冒险基本信息',
        'hd293Rwd' => '寻宝大冒险 - 领取圈数奖励',
        'hd293Task' => '寻宝大冒险 - 领取每日重置任务',
        'hd293Run' => '寻宝大冒险 - 要骰子转圈圈',
        'hd294Info' => '招财进宝基本信息',
        'hd294Zao' => '招财进宝  -- 摇奖',
        'hd294log' => '招财进宝  -- 日志',
        'hd294Get' => '招财进宝  -- 领取',
        'hd294Set' => '招财进宝  --单抽消费提示',
        'hd294paihang' => '招财进宝-排行和奖励',
        'hdGetXSRank' => '获取限时排行榜',
        'hd6121Rwd' => '天天秒杀',
        'hd6122Rwd' => '兑换商城-兑换奖励',
        'hd6136buy' => '皇子应援-商城单品购买',
        'hd6136exchange' => '皇子应援活动-积分兑换',
        'hd6136play' => '皇子应援活动-应援',
        'hd6137Rwd' => '皇子应援-领取奖励',
        'hd6152Rwd' => '兑换活动-兑换奖励',
        'hd6168Rwd' => '连续每日充值-领取奖励(1)',
        'hd6168TotalRwd' => '连续每日充值-领取奖励(n)',
        'hd6169Yao' => '命盘-摇奖',
        'hd6123Add' => '盛装出席-增加次数',
        'hd6180Buy' => '超值礼包',
        'hd6182RwdCharge' => '身份大礼-购买档次奖励',
        'hd6211cash' => '二十四节气-元宝购买',
        'hd6228buy' => '读书节-商城购买',
        'hd6227buy' => '幸运命盘-商城购买',
        'hd6224change' => '舞狮大会-任务刷新',
        'hd6222buy' => '游山玩水 - 商品购买',
        'hd6231buy' => '抢糕点 - 商品购买',
        'hd6229buy' => '禾缘 - 商品购买',
        'hd6241buy' => '代言人活动 - 商品购买',
        'hd8011UpLevel' => '贵人令-购买等级',
        'hd8016UpLevel' => '新贵人令-购买等级',
        'hd8018Rwd' => '三消活动-领取积分奖励',
        'hd8018PveRwd' => '三消活动-领取关卡奖励',
        'hd8018buy' => '三消活动- 商品购买',
        'hd8018exchange' => '三消活动- 兑换',
        'hd8018Play' => '三消活动-消除',
        'hd8018Recovery' => '三消活动-使用体力药水',
        'hd8029OpenMoon' => '打月亮-开启月亮',
        'hd8029buy' => '打月亮-商品购买',

    ),
    'card' => array (
        'quick_buy' => '卡牌 - 购买抽卡消耗',
    ),
    'order' => array (
        'getOrderId' => '获取订单id',
        'orderBack' => '充值客户端回调请求=>用于同步信息',
        'AppFailCallback' => '因为苹果支付成功回调前不与服务端通信，故出现错误很难查询，',
    ),
    'jiulou' => array (
        'jlInfo' => '酒楼信息',
        'yhFind' => '编号赴会-查询',
        'yhGo' => '编号赴会-前往',
        'yhChi' => '吃宴会',
        'shopChange' => '商店积分兑换-兑换',
        'shopRefresh' => '商店-刷新',
        'yhHold' => '举办宴会',
        'jlRanking' => '酒楼-排行榜',
    ),
    'qiandao' => array (
        'rwd' => '签到领奖',
    ),
    'fuli' => array (
        'qiandao' => '签到领奖',
        'fcho' => '首充领奖',
        'vip' => 'VIP领奖',
        'mooncard' => '月卡/年卡',
        'buy' => 'VIP特惠礼包',
        'buyZeroGift' => '购买零元购礼包',
    ),
    'oprefresh' => array (
        'id' => '宴会id',
    ),
    'opchange' => array (
        'id' => '物品标识id',
    ),
    'opinfo' => array (
        'id' => '宴会id',
    ),
    'chengjiu' => array (
        'rwd' => '领取成就奖励',
    ),
    'club' => array (
        'clubCreate' => '创建宫殿',
        'clubRand' => '随机入宫',
        'clubFind' => '查询宫殿',
        'clubApply' => '申请入宫',
        'clubList' => '宫殿榜单/排行榜',
        'clubInfo' => '宫殿信息',
        'clubName' => '宫殿名字修改',
        'clubPwd' => '宫殿密码修改',
        'clubInfoSave' => '宫殿信息保存',
        'isJoin' => '是否允许其他玩家随机加入',
        'applyList' => '申请列表',
        'noJoin' => '拒绝加入宫殿',
        'yesJoin' => '同意加入',
        'outClub' => '退出宫殿',
        'delClub' => '删除宫殿',
        'dayGongXian' => '每日贡献',
        'memberPost' => '职位变更/逐出宫殿',
        'shopList' => '贡献兑换商店列表',
        'shopBuy' => '贡献兑换商店=>兑换',
        'clubBossInfo' => '宫殿boss信息',
        'clubBossOpen' => '开启宫殿副本',
        'clubBossPK' => '宫殿boss-pk',
        'clubHeroCone' => '宫殿伙伴复活',
        'clubBosslog' => 'boss未被打死, 每个伙伴的日志',
        'clubBossHitList' => '宫殿boss战报列表=>伤害排行',
        'transList' => '转让列表',
        'transWang' => '转让宫主',
        'kuaPKinfo' => '宫殿战信息',
        'kuaPKCszr' => '宫殿战参赛阵容',
        'kuaPKAdd' => '宫殿战伙伴派遣/更换',
        'kuaPKBack' => '宫殿战伙伴撤回',
        'kuaPKzr' => '宫殿战宫殿战pk阵容',
        'kuaPKusejn' => '宫殿战宫殿战pk使用锦囊',
        'kuaLookWin' => '宫殿战宫殿战pk获胜/失败弹窗',
        'kuaPKbflog' => '宫殿战宫殿战pk播放日志',
        'kuaLookHit' => '宫殿战宫殿战pk伤害排行',
        'kuaPKrwdinfo' => '宫殿战宫殿战pk奖励信息',
        'kuaPKrwdget' => '宫殿战宫殿战pk奖励领取',
    ),
    'ualookwin' => array (
        'cid' => '宫殿id',
    ),
    'ualookhit' => array (
        'cid' => '宫殿id',
    ),
    'uapkrwdget' => array (
        'id' => '1: 个人奖励   2:宫殿奖励',
    ),
    'uapkrwdinfo' => array (
        'id' => 'id',
    ),
    'uapkusejn' => array (
        'id' => '锦囊id',
        'heroid' => '伙伴id(使用伏兵锦囊)',
    ),
    'uapkadd' => array (
        'hid' => '伙伴id',
    ),
    'uapkbflog' => array (
        'cid' => '宫殿id',
    ),
    'uapkback' => array (
        'hid' => '伙伴id',
    ),
    'uapkcszr' => array (
        'cid' => '宫殿id',
    ),
    'uapkinfo' => array (
        'cid' => '宫殿id',
    ),
    'oplist' => array (
        'cid' => '宫殿id',
    ),
    'opbuy' => array (
        'id' => '物品标识id',
    ),
    'laofang' => array (
        'bianDa' => '打或者一键打',
    ),
    'xunfang' => array (
        'xunfang' => '旧寻访',
        'recover' => '出城-恢复体力',
        'zzHand' => '出城-手动占卜',
        'xunfan' => '出城-随处看看',
        'yunshi' => '出城-自动占卜',
    ),
    'chenghao' => array (
        'setChengHao' => '设置称号',
        'offChengHao' => '取消称号',
        'wyrwd' => '王爷领取奖励',
    ),
    'fengxiandian' => array (
        'qingAn' => '奉先殿请安',
        'setDeclarate' => '设置宣言',
    ),
    'wordboss' => array (
        'wordboss' => '打开世界BOSS',
        'hitmenggu' => '蒙古军打',
        'hitgeerdan' => '郊祀献礼 献礼',
        'goFightmg' => '蒙古军进入战斗',
        'goFightg2d' => '葛二蛋进入战斗',
        'scoreRank' => '点击积分击杀榜',
        'g2dHitRank' => '点击伤害排行',
        'shopBuy' => '积分兑换',
        'comebackmg' => '蒙古 复活伙伴',
        'comebackg2d' => '郊祀献礼 复活伙伴',
    ),
    'login' => array (
        'loginAccount' => '登入',
    ),
    'guide' => array (
        'login' => '进入游戏',
        'randName' => '随机名字',
        'setUinfo' => '取名字',
        'guide' => '新手引导保存',
        'guideUpguan' => '新手引导平民升官',
        'kefu' => '客服信息',
    ),
    'user' => array (
        'jingYing' => '办差操作',
        'jingYingLing' => '使用办差令',
        'jingYingAll' => '一键办差',
        'qzam' => '勤政爱民',
        'zhengWu' => '日常处理',
        'zhengWuLing' => '日常令',
        'pve' => '地图打小兵',
        'pvb' => '地图BOSS',
        'pvb2' => '全军出击',
        'comeback' => '打地图BOSS伙伴复活',
        'adok' => '心跳请求',
        'randName' => '随机名字',
        'getFuserMember' => '获取其他玩家信息',
        'shengguan' => '升官',
        'resetName' => '改名',
        'resetImage' => '改头像',
        'refjingying' => '办差刷新',
        'refwife' => '知己刷新',
        'refxunfang' => '寻访刷新',
        'refson' => '徒弟刷新',
        'getuback' => '获取用户场景',
        'setuback' => '设置用户场景',
        'lockClothe' => '主角换装',
        'qifu' => '祈福',
        'qifuTen' => '祈福十次',
    ),
    'hero' => array (
        'upgrade' => '升级伙伴',
        'upgradeTen' => '伙伴连升十级',
        'upsenior' => '伙伴提拔',
        'upzzskill' => '伙伴资质技能升级',
        'uppkskill' => '伙伴PK技能升级',
        'upghskill' => '伙伴光环技能升级',
        'giveGift' => '伙伴送礼',
        'upStar' => '伙伴升星',
        'tokenActivation' => '伙伴信物激活',
        'tokenUpLv' => '伙伴信物升级',
        'fetterActivation' => '伙伴羁绊激活',
        'xxoo' => '出游',
        'sjcy' => '随机出游',
        'xxoonobaby' => '问候',
        'sjxo' => '随机问候',
        'weige' => '恢复精力',
        'hfjiaqi' => '恢复假日',
        'visit' => '定向拜访',
    ),
    'item' => array (
        'useitem' => '使用道具,item,item2 类型',
        'useforhero' => '使用道具到伙伴身上,hero,类型',
        'hecheng' => '道具合成',
        'itemlist' => '道具列表',
    ),
    'wife' => array (
        'xxoo' => '出游',
        'sjcy' => '随机出游',
        'yjxxoogetbaby' => '一键出游',
        'xxoonobaby' => '问候',
        'sjxo' => '随机问候',
        'yjxo' => '一键问候',
        'reward' => '赏赐',
        'upskill' => '升级知己技能',
        'weige' => '恢复精力',
        'hfjiaqi' => '恢复假日',

    ),
    'school' => array (
        'buydesk' => '购买学位',
        'start' => '开始学习',
        'over' => '完成学习',
        'allover' => '一键完成',
        'speedFinish' => '学院-加速完成',
    ),
    'son' => array (
        'buyseat' => '购买徒弟席位',
        'buyLilianSeat' => '购买徒弟历练席位',
        'liLianSon' => '徒弟历练',
        'liLianReward' => '徒弟历练领取奖励',
        'sonname' => '取名字',
        'rname' => '改名字',
        'play' => '培养',
        'onfood' => '恢复活力',
        'allplay' => '一键培养',
        'allfood' => '一键恢复',
        'keju' => '科举',
        'meipo' => '点击媒婆',
        'tiqin' => '提亲',
        'getTiqin' => '刷新对我的提请请求',
        'zhaoqin' => '刷新全服招亲表',
        'jiehun' => '结婚 从全服招亲列表中 选中一个人结婚',
        'agree' => '同意提亲请求 选中来提亲的 进行联姻',
        'pass' => '拒绝提亲请求',
        'allpass' => '拒绝所有提亲请求',
        'cancel' => '终止联姻/全服提亲撤回/个人提亲撤回/被拒绝撤回/超时撤回',
        'rstzhaoqin' => '立即刷新全服招亲表',
        'yjLiLianSon' => '一键选择徒弟历练',
        'speedFinish' => '历练-加速完成',
    ),
    'ranking' => array (
        'paihang' => '刷新排行榜',
        'mobai' => '膜拜123',
    ),
    'shop' => array (
        'shoplist' => '商城列表',
        'shopLimit' => '单品限购',
        'shopGift' => '特惠礼包',
    ),
    'yamen' => array (
        'yamen' => '进入宫斗',
        'chushi' => '使用出使令',
        'tiaozhan' => '使用挑战卡',
        'fuchou' => '复仇',
        'zhuisha' => '追杀',
        'findzhuisha' => '追杀查询',
        'pizun' => '批准进入战斗',
        'fight' => '选一个人打',
        'seladd' => '宫斗-选择加成',
        'getrwd' => '选择翻拍奖励',
        'getrank' => '刷新排行榜',
        'yamenhistory' => '宫斗日志历史信息',
        'clearCD' => '宫斗-清除等待cd',
    ),
    'chat' => array (
        'sev' => '公共频道',
        'sevhistory' => '公共频道历史信息',
        'club' => '工会频道',
        'kuafu' => '跨服频道',
        'clubhistory' => '工会频道历史信息',
        'kuafuhistory' => '跨服频道历史信息',
        'addblacklist' => '加入黑名单',
        'subblacklist' => '移除黑名单',
    ),
    'code' => array (
        'exchange' => '兑换码信息',
    ),
    'hunt' => array (
        'hunt' => '打开狩猎',
        'play' => '打猎物',
        'jf_rwd' => '领取全服奖励',
        'rankRwd' => '排行奖励信息',
        'allDressRwd' => '全服奖励信息',
        'paihang' => '排行榜',
        'isOpen' => '是否开启',
    ),
    'taofa' => array (
        'taofa' => '讨伐-进入讨伐',
        'play' => '讨伐-打',
        'paihang' => '排行榜',
        'rootPlay' => '一键讨伐-打',
        'rootInfo' => '一键讨伐-信息',
    ),
    'hanlin' => array (
        'listinfo' => '刷新大厅',
        'opendesk' => '新建房间',
        'comein' => '进入房间',
        'sitdown' => '加入空位置',
        'ti' => '踢人打架',
        'find' => '查询房间',
        'upskill' => '升级技能',
        'suoding' => '保护玩家',
    ),
    'trade' => array (
        'trade' => '获取丝绸之路信息',
        'play' => '丝绸之路-pk',
        'rootPlay' => '丝绸之路-一键通商',
        'paihang' => '排行榜',
    ),
    'friends' => array (
        'flist' => '好友列表',
        'fapply' => '好友-申请',
        'fapplylist' => '好友申请列表',
        'fok' => '好友申请列表 - 同意',
        'fno' => '好友申请列表 - 拒绝',
        'fsub' => '好友列表 - 删除',
        'qjlist' => '亲家列表',
        'qjvisit' => '亲家拜访0:一键拜访>0:uid拜访',
        'ffchat' => '获取私聊信息',
        'fschat' => '发送私聊',
        'fssub' => '私聊列表 - 删除私聊玩家',
        'fhistory' => '输出历史列表',
        'frchat' => '刷新私聊信息',
    ),
    'kuayamen' => array (
        'comehd' => '进入活动',
        'yamen' => '进入宫斗',
        'chushi' => '使用出使令',
        'tiaozhan' => '使用挑战卡',
        'fuchou' => '复仇',
        'zhuisha' => '追杀',
        'findzhuisha' => '追杀查询',
        'pizun' => '批准进入战斗',
        'getSevRwd' => '领取本服奖励',
        'fight' => '选一个人打',
        'seladd' => '选择加成',
        'getrwd' => '选择翻牌奖励',
        'getRank' => '刷新排行榜',
        'yamenhistory' => '宫斗日志历史信息',
        'kuafu' => '跨服频道',
        'kuafuhistory' => '跨服频道历史信息',
        'getYxRank' => '获取预选赛排名',
        'getMyRank' => '获取我的排名和本服排名信息',
    ),
    'gzj' => array (
        'gzj' => '国子监-进入',
        'addDesk' => '国子监-购买读书位',
        'startStudy' => '国子监-开始学习',
        'bribery' => '国子监-行贿',
        'overWork' => '国子监-毕业',
        'alloverWork' => '国子监-一键毕业',
        'getdayreward' => '国子监-获取每日奖励-个人',
        'alldayreward' => '国子监-一键获取每日奖励',
    ),
    'kitchen' => array (
        'buyStove' => '御膳房-购买火炉',
        'food' => '御膳房-开始煮饭',
        'buyFood' => '御膳房-购买食材',
        'over' => '御膳房-完成煮饭',
    ),
    'boite' => array (
        'jlInfo' => '酒楼信息',
        'yhFind' => '编号赴会-查询',
        'yhGo' => '编号赴会-前往',
        'yhChi' => '吃宴会',
        'shopChange' => '商店积分兑换-兑换',
        'shopRefresh' => '商店-刷新',
        'yhHold' => '举办宴会',
        'jlRanking' => '酒楼-排行榜',
    ),
    'admin' => array (
        'userChange' => '后台操作-修改用户信息',
        'userItem' => '后台操作-增加道具',
        'hero' => '后台操作-增加伙伴',
        'wife' => '后台操作-增加知己',
        'recharge_fuli' => '后台操作-充值福利',
    ),
    'treasure' => array (
        'win' => '珍宝阁整理-直接过关',
        'clipTrea' => '珍宝阁整理-获取线索奖励',
        'trun' => '珍宝阁整理-翻牌',
        'reset' => '珍宝阁整理-重置关卡',
        'addCount' => '珍宝阁整理-购买翻牌次数',
        'treasure' => '珍宝阁整理-获取奖励',
    ),
    'scpoint' => array (
        'story' => '主线剧情',
        'zwStory' => '日常剧情',
        'jyStory' => '办差剧情',
        'emailStory' => '飞鸽剧情',
        'emailSonStory' => '历练飞鸽剧情',
        'heroOrwifeStory' => '闲谈剧情',
    ),
    'flower' => array (
        'open' => '御花园-解锁花盆',
        'protectCover' => '御花园-保护罩',
    ),
    'fapei' => array (
        'addDesk' => '闲云宫-增加位置',
        'recall' => '闲云宫-召回伙伴',
    ),
    'fuyue' => array (
        'getFuyueInfo' => '赴约-获取信息',
        'startStory' => '赴约-开始故事',
        'startFight' => '赴约-开始战斗',
        'saveStory' => '赴约-保存故事',
        'delStory' => '赴约-删除故事',
        'pickClearanceAward' => '赴约-领取最终奖励',
        'noSaveStory' => '赴约-不保存',
        'exchange' => '赴约-兑换',
        'buyCount' => '赴约-购买道具',
    
    ),
    'banchai' => array (
        'getInfo' => '办差-获取信息',
        'startBanchai' => '办差-开始办差',
        'chooseAnswer' => '办差-选择结果',
        'revive' => '办差-复活',
        'abandonRevive' => '办差-放弃复活',
        'pickFinalAward' => '办差-领取结局奖励',
        'useBanchaiLing' => '办差-购买办差令',
        'buyCount' => '办差-购买开始次数',
        'revive' => '办差-复活',
    ),
    'sevendays' => array (
        'buyValueGift' => '七日庆典-购买超值购礼包',
        'sevenSupplySign' => '七日庆典-补签'
    ),
    'business' => array (
        'buyCount' => '行商-购买次数',
        'nextTravel' => '行商-下一个城市',
        'pickFinalAward' => '行商-提交订单',
    ),
    'baowu' => array (
        'quick_buy' => '四海奇珍-购买消耗道具',
    ),

);