<?php
//用户换装
return array (
  1 => 
  array (
    'id' => 1,
    'clother' => 
    array (
      0 => 1,
      1 => 201,
    ),
    'name' => '布衣',
    'lvup' => 1,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '青青子衿，悠悠我心。但为君故，沉吟至今。',
    'type' => 3,
    'icon' => 'body_0_201',
    'unlock' => 1,
    'lvup2' => 1,
    'cardSlot' => 1,
    'storyname1' => '吉祥布庄',
    'story1' => '长安城中有一处“吉祥布庄”，价格便宜，纹样却是十分别致，是城中平民百姓最爱光顾之处。',
    'unlocktype1' => 1,
    'para1' => 201,
    'storyname2' => '刘家二娘',
    'story2' => '布庄纹样出自掌柜刘吉祥之手。刘家二娘尤善丹青，当年便是以豆蔻年纪随手画出的纹样将生意萧条的布庄救回。',
    'unlocktype2' => 1,
    'para2' => 1,
    'storyname3' => '生意人',
    'story3' => '刘吉祥声名愈盛，就连宫中制造局也曾请她绘制纹样。可她仍坚持经营着吉祥布庄，十多年来从未涨价。',
    'unlocktype3' => 1,
    'para3' => 1,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  2 => 
  array (
    'id' => 2,
    'clother' => 
    array (
      0 => 2,
      1 => 202,
    ),
    'name' => '应钟服',
    'lvup' => 2,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着应钟御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_1',
    'unlock' => 1,
    'lvup2' => 2,
    'cardSlot' => 2,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  3 => 
  array (
    'id' => 3,
    'clother' => 
    array (
      0 => 3,
      1 => 203,
    ),
    'name' => '无射服',
    'lvup' => 3,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着无射御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_202',
    'unlock' => 1,
    'lvup2' => 3,
    'cardSlot' => 3,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  4 => 
  array (
    'id' => 4,
    'clother' => 
    array (
      0 => 4,
      1 => 204,
    ),
    'name' => '南吕服',
    'lvup' => 4,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着南吕御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_203',
    'unlock' => 1,
    'lvup2' => 4,
    'cardSlot' => 4,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  5 => 
  array (
    'id' => 5,
    'clother' => 
    array (
      0 => 5,
      1 => 205,
    ),
    'name' => '夷则服',
    'lvup' => 5,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着夷则御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_204',
    'unlock' => 1,
    'lvup2' => 5,
    'cardSlot' => 5,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  6 => 
  array (
    'id' => 6,
    'clother' => 
    array (
      0 => 6,
      1 => 206,
    ),
    'name' => '林钟服',
    'lvup' => 6,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着林钟御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_205',
    'unlock' => 1,
    'lvup2' => 6,
    'cardSlot' => 6,
    'storyname1' => '御史台',
    'story1' => '御史台坐落在未央宫东北一隅，环境清幽，供御史大夫居住与处理政务。',
    'unlocktype1' => 1,
    'para1' => 206,
    'storyname2' => '御史台·槐树',
    'story2' => '御史台院是一片开阔的空地，只有一棵槐树格格不入地立在中间。这槐树自未央宫建立起便已经生长在这里。',
    'unlocktype2' => 1,
    'para2' => 6,
    'storyname3' => '御史台·槐花',
    'story3' => '每至初春，老槐树上便有泛青的槐花渐渐散发出幽香。待到槐花长成，御史台上下便将槐花摘下，制成糕点。',
    'unlocktype3' => 1,
    'para3' => 6,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  7 => 
  array (
    'id' => 7,
    'clother' => 
    array (
      0 => 7,
      1 => 207,
    ),
    'name' => '蕤宾服',
    'lvup' => 7,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着蕤宾御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_206',
    'unlock' => 1,
    'lvup2' => 7,
    'cardSlot' => 7,
    'storyname1' => '御史台·荷花',
    'story1' => '御史台的后院与宫内潋滟池相连，池中种着荷花，夏日从御史台书房窗口向外看去，便能看到一片映日荷花的景象。',
    'unlocktype1' => 1,
    'para1' => 207,
    'storyname2' => '夏日烦恼',
    'story2' => '诚然临湖而居在夏日也十分凉爽，风景亦是优美，可同样会吸引来许多蚊虫。',
    'unlocktype2' => 1,
    'para2' => 7,
    'storyname3' => '奇香',
    'story3' => '为了驱逐蚊虫，御史台上下常燃着一种可退蚊虫的奇香，直到扰人的夏季过后，御史台还能闻到那若有似无的香味。',
    'unlocktype3' => 1,
    'para3' => 7,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  8 => 
  array (
    'id' => 8,
    'clother' => 
    array (
      0 => 8,
      1 => 208,
    ),
    'name' => '仲吕服',
    'lvup' => 8,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着仲吕御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_207',
    'unlock' => 1,
    'lvup2' => 8,
    'cardSlot' => 8,
    'storyname1' => '御史台·后院',
    'story1' => '御史台后院栽种着不少花草。本朝御史大夫不拘小节，不论是名花异草还是路边野花，全都随性种在一处。',
    'unlocktype1' => 1,
    'para1' => 208,
    'storyname2' => '墙角幽兰·一',
    'story2' => '渊帝曾赐给御史大夫几株名贵兰花，御史大夫见后院中已无空地，便不顾宫人挖掉野花的劝说，将兰花栽种在墙角。',
    'unlocktype2' => 1,
    'para2' => 8,
    'storyname3' => '墙角幽兰·二',
    'story3' => '这过于随意的后院终于被渊帝看到，渊帝看着自己被挪到角落里的兰花，只是哈哈一笑，并未怪罪。',
    'unlocktype3' => 1,
    'para3' => 8,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  9 => 
  array (
    'id' => 9,
    'clother' => 
    array (
      0 => 9,
      1 => 209,
    ),
    'name' => '姑洗服',
    'lvup' => 9,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着姑洗御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_208',
    'unlock' => 1,
    'lvup2' => 9,
    'cardSlot' => 9,
    'storyname1' => '兰台一日·一',
    'story1' => '兰台在御史台不远处，典藏着不少图书典籍，亦或是各朝档案刑录，若非允许，不得随意翻阅。',
    'unlocktype1' => 1,
    'para1' => 209,
    'storyname2' => '兰台一日·二',
    'story2' => '御史大夫每日早晨与兰台官员一起在兰台处理各类事务，上至官员弹劾，下至百姓纠纷。',
    'unlocktype2' => 1,
    'para2' => 9,
    'storyname3' => '兰台一日·三',
    'story3' => '清闲时日，兰台中的几位女官也会如寻常规格小姐那般，在御史大夫的带领下一同品茗闲聊，交流些趣事。',
    'unlocktype3' => 1,
    'para3' => 9,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  10 => 
  array (
    'id' => 10,
    'clother' => 
    array (
      0 => 10,
      1 => 210,
    ),
    'name' => '夹钟服',
    'lvup' => 10,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着夹钟御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_209',
    'unlock' => 2,
    'lvup2' => 10,
    'cardSlot' => 10,
    'storyname1' => '赏荷之日·一',
    'story1' => '潋滟池中荷花开放的季节，兰台上下会择一日午后一同在池边凉亭赏花。',
    'unlocktype1' => 1,
    'para1' => 210,
    'storyname2' => '赏荷之日·二',
    'story2' => '兰台官员坐在亭中，饮茶对诗。若遇到仍为公务争论不休者，御史大夫则会亲自出面斟茶，让对方“自罚三杯”',
    'unlocktype2' => 1,
    'para2' => 10,
    'storyname3' => '赏荷之日·三',
    'story3' => '从前兰台众人喝的是御史台珍藏的清酒，当日便喝得酩酊大醉，甚至惊动了渊帝，渊帝便下令禁止兰台饮酒。',
    'unlocktype3' => 2,
    'para3' => 10,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  11 => 
  array (
    'id' => 11,
    'clother' => 
    array (
      0 => 11,
      1 => 211,
    ),
    'name' => '太簇服',
    'lvup' => 11,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着太簇御史身份的官服',
    'type' => 1,
    'icon' => 'body_0_210',
    'unlock' => 2,
    'lvup2' => 11,
    'cardSlot' => 11,
    'storyname1' => '协理朝政',
    'story1' => '御史大夫虽有协理朝政之权，可新任命的御史大夫一无背景，二无政绩，难免让群臣无法信服。',
    'unlocktype1' => 1,
    'para1' => 211,
    'storyname2' => '鸡毛蒜皮',
    'story2' => '若是只靠处理那些鸡毛蒜皮的小事，御史大夫恐怕仍然无法服众，最多算是无功无过。',
    'unlocktype2' => 1,
    'para2' => 11,
    'storyname3' => '御史上任',
    'story3' => '然而御史大夫标新立异，不拘一格，不怕得罪人地解决了不少累积已久的旧案。',
    'unlocktype3' => 2,
    'para3' => 11,
    'storyname4' => '不怕麻烦',
    'story4' => '御史大夫这样的举动却为她带来了新的麻烦——来自朝中一些势力明里暗里的为难。然而御史大夫从来都不怕麻烦。',
    'unlocktype4' => 2,
    'para4' => 5,
    'storyname5' => '顺势为之',
    'story5' => '所谓的“麻烦”被御史大夫一一化解，并转化成了她的“功绩”，自此御史大夫的等级也水涨船高。',
    'unlocktype5' => 2,
    'para5' => 10,
  ),
  15 => 
  array (
    'id' => 15,
    'clother' => 
    array (
      0 => 15,
      1 => 215,
      2 => 315,
    ),
    'name' => '梅花三弄',
    'lvup' => 15,
    'show_time' => '2019-08-16 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '日暮诗成天又雪，与梅并作十分春。',
    'type' => 3,
    'icon' => 'body_0_15',
    'unlock' => 3,
    'lvup2' => 15,
    'cardSlot' => 15,
    'storyname1' => '北郊·红梅',
    'story1' => '寒冬腊月之时，长安城草木凋敝，仿佛失了一层颜色，而北郊的红梅却在此时盛开。',
    'unlocktype1' => 1,
    'para1' => 315,
    'storyname2' => '新衣',
    'story2' => '年关将近，城中百姓都开始添置新衣。专为过年准备的红衣仍是有些奢侈，毕竟一年到头哪有那么多着红衣的时候。',
    'unlocktype2' => 1,
    'para2' => 215,
    'storyname3' => '红绸',
    'story3' => '为新衣绑上红色腰带、或是系上平安结，便逐渐成了百姓们庆祝新年的传统。',
    'unlocktype3' => 1,
    'para3' => 15,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  16 => 
  array (
    'id' => 16,
    'clother' => 
    array (
      0 => 16,
      1 => 216,
      2 => 316,
    ),
    'name' => '陌上花开',
    'lvup' => 16,
    'show_time' => '2019-08-16 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '陌上花开，可缓缓归矣。',
    'type' => 3,
    'icon' => 'body_0_16',
    'unlock' => 3,
    'lvup2' => 16,
    'cardSlot' => 16,
    'storyname1' => '东郊·桃花',
    'story1' => '东郊有一片桃花林，是高祖皇帝命人为皇后所种，如今变成了寻常百姓也能赏景游玩的地方。',
    'unlocktype1' => 1,
    'para1' => 316,
    'storyname2' => '东郊·孤女',
    'story2' => '东郊住着的哑巴在桃花林里捡到一个小姑娘，一直抚养长大。哑巴不识字，城郊的百姓便都称少女为春桃。',
    'unlocktype2' => 1,
    'para2' => 216,
    'storyname3' => '春桃',
    'story3' => '春桃出落得楚楚可人，向哑巴提亲的人络绎不绝，春桃却一一拒绝。',
    'unlocktype3' => 1,
    'para3' => 16,
    'storyname4' => '陌上花',
    'story4' => '不知何时起，春桃每日都会去那片桃花林，独自一人徘徊在花间。而春桃却说，她在等一个人。',
    'unlocktype4' => 2,
    'para4' => 5,
    'storyname5' => '缓缓归',
    'story5' => '年复一年，直到驻扎西北的渊军凯旋回朝。不过几日，一位年轻的将领来到东郊，向哑巴提亲，迎娶了春桃。',
    'unlocktype5' => 2,
    'para5' => 10,
  ),
  18 => 
  array (
    'id' => 18,
    'clother' => 
    array (
      0 => 18,
      1 => 218,
      2 => 318,
    ),
    'name' => '剑舞莲动',
    'lvup' => 18,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '红莲之中，剑光闪动，掀起携着香味的风',
    'type' => 2,
    'icon' => 'body_0_18',
    'unlock' => 3,
    'lvup2' => 18,
    'cardSlot' => 18,
    'storyname1' => '长乐乐坊',
    'story1' => '长乐乐坊是长安城中风雅之处，不论达官显贵还是名流雅士，皆爱来此一边小酌、一边欣赏乐舞。',
    'unlocktype1' => 1,
    'para1' => 318,
    'storyname2' => '莲姬',
    'story2' => '长乐乐坊最为著名的则是莲姬。长安流传着许多赞美莲姬舞姿的诗词，众人不远千里慕名而来，就是为看她一舞。',
    'unlocktype2' => 1,
    'para2' => 218,
    'storyname3' => '剑舞',
    'story3' => '莲姬最为出名的，就是她的莲上剑舞。玉足在莲花上轻踩而过，只留下一片涟漪。',
    'unlocktype3' => 1,
    'para3' => 18,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  20 => 
  array (
    'id' => 20,
    'clother' => 
    array (
      0 => 20,
      1 => 220,
      2 => 320,
    ),
    'name' => '小仙鹟',
    'lvup' => 20,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 3,
    'icon' => 'body_0_20',
    'unlock' => 3,
    'lvup2' => 20,
    'cardSlot' => 20,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  28 => 
  array (
    'id' => 28,
    'clother' => 
    array (
      0 => 28,
      1 => 228,
      2 => 328,
    ),
    'name' => '月下潜行',
    'lvup' => 28,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '月下壶天游未尽，广寒宫是波中影。',
    'type' => 2,
    'icon' => 'body_0_28',
    'unlock' => 2,
    'lvup2' => 28,
    'cardSlot' => 28,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  33 => 
  array (
    'id' => 33,
    'clother' => 
    array (
      0 => 33,
      1 => 233,
      2 => 333,
    ),
    'name' => '桃之灼灼',
    'lvup' => 33,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '桃之夭夭，灼灼其华。之子于归，宜其室家。',
    'type' => 4,
    'icon' => 'body_0_33',
    'unlock' => 3,
    'lvup2' => 33,
    'cardSlot' => 33,
    'storyname1' => '似火·一',
    'story1' => '她从南疆而来，带着一匹名为“火云卷”的绸缎。相传这绸缎远看如同烈火，在黑暗中也可发出耀目光芒。',
    'unlocktype1' => 1,
    'para1' => 333,
    'storyname2' => '似火·二',
    'story2' => '没有人知道她为何而来，也没有人知道她要带着这匹布去向何处。王公贵族想从她手中买下这火云卷，却无人成功。',
    'unlocktype2' => 1,
    'para2' => 233,
    'storyname3' => '似火·三',
    'story3' => '她被卷入一场纷争，只因有人想抢夺那匹火云卷。不久之后，她在众目睽睽之下，抱着那装火云卷的匣子跳进湖中。',
    'unlocktype3' => 1,
    'para3' => 33,
    'storyname4' => '似火·四',
    'story4' => '前来争夺之人争相恐后将匣子捞出，却发现里面空空如也。这时天下人才醒悟——或许世上本就没有“火云卷”。',
    'unlocktype4' => 2,
    'para4' => 5,
    'storyname5' => '似火·终',
    'story5' => '三年后，有人看到一名女子独自穿过西北荒原。那时正是破晓，她一身红衣如同烈火，在黑暗中燃烧出灿烂的光芒。',
    'unlocktype5' => 2,
    'para5' => 10,
  ),
  34 => 
  array (
    'id' => 34,
    'clother' => 
    array (
      0 => 34,
      1 => 234,
    ),
    'name' => '碎玉琼花',
    'lvup' => 34,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '凤州宫柳昔曾攀，亦醉琼花芍药间。',
    'type' => 1,
    'icon' => 'body_0_34',
    'unlock' => 3,
    'lvup2' => 34,
    'cardSlot' => 34,
    'storyname1' => '琼花·一',
    'story1' => '天子一统天下前，曾因躲避追杀藏在一座破庙中。',
    'unlocktype1' => 1,
    'para1' => 234,
    'storyname2' => '琼花·二',
    'story2' => '那破庙后院有几丛琼花，天子见之，心生怜爱，曾说有此花为伴，破庙也不觉简陋。',
    'unlocktype2' => 1,
    'para2' => 34,
    'storyname3' => '琼花·三',
    'story3' => '待天下统一、天子重返未央宫后，便命人将那琼花带到长安，栽种在寝宫门前。',
    'unlocktype3' => 2,
    'para3' => 5,
    'storyname4' => '琼花·四',
    'story4' => '然而那在破庙野地都能盛放的花，来到宫中后却日渐凋敝枯萎了。',
    'unlocktype4' => 2,
    'para4' => 10,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  35 => 
  array (
    'id' => 35,
    'clother' => 
    array (
      0 => 35,
      1 => 235,
    ),
    'name' => '黄金台',
    'lvup' => 35,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '御史大夫最为正式的官服，庄重而不失轻快，尽显御史大夫的尊贵身份',
    'type' => 1,
    'icon' => 'body_0_35',
    'unlock' => 3,
    'lvup2' => 35,
    'cardSlot' => 35,
    'storyname1' => '黄金台·一',
    'story1' => '宫中女官依照十二律阶，皆有统一形制的官服。而御史大夫地位特殊，还有一套独属于自己的御史服。',
    'unlocktype1' => 1,
    'para1' => 235,
    'storyname2' => '黄金台·二',
    'story2' => '御史服比之律阶官服少了几分繁复，却更显庄重，是怕麻烦的御史大夫最常的选择。',
    'unlocktype2' => 1,
    'para2' => 35,
    'storyname3' => '黄金台·三',
    'story3' => '即便穿着官服，下朝后的御史大夫也总是会做些“出乎意料”的举动，而这身衣服往往会成为阻碍。',
    'unlocktype3' => 2,
    'para3' => 5,
    'storyname4' => '黄金台·四',
    'story4' => '对于此，御史台的侍从们想到了一个解决方法——他们为御史大夫准备了三套一模一样的官服！',
    'unlocktype4' => 2,
    'para4' => 10,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  36 => 
  array (
    'id' => 36,
    'clother' => 
    array (
      0 => 36,
      1 => 236,
    ),
    'name' => '沧海月明',
    'lvup' => 36,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '沧海月明珠有泪，蓝田日暖玉生烟',
    'type' => 2,
    'icon' => 'body_0_36',
    'unlock' => 3,
    'lvup2' => 36,
    'cardSlot' => 36,
    'storyname1' => '南海·仙山',
    'story1' => '传说南海有仙山。天子令能人异士寻觅多年都未曾寻到仙山踪迹，却流传出了不少海中其他传说。',
    'unlocktype1' => 1,
    'para1' => 236,
    'storyname2' => '南海·衔珠',
    'story2' => '有人曾在南海海岸捡到过一条银色小鱼，心存不忍遂放生海中。三年后，一条银色龙鲤衔着珍珠回报于此人。',
    'unlocktype2' => 1,
    'para2' => 36,
    'storyname3' => '南海·鲛人',
    'story3' => '海中有鲛人，其眼泣而生珠。传闻鲛人所织龙绡如同鱼鳞一般有珠玉光泽，且不沾水，是世人梦寐以求的宝物。',
    'unlocktype3' => 2,
    'para3' => 5,
    'storyname4' => '南海·龙绡',
    'story4' => '世上是否真有鲛人不得而知，可据南海居民所言，古今确实时有贵人登岸，华服上流淌着鱼鳞珠玉般的光泽。',
    'unlocktype4' => 2,
    'para4' => 10,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  37 => 
  array (
    'id' => 37,
    'clother' => 
    array (
      0 => 37,
      1 => 237,
      2 => 337,
    ),
    'name' => '蝴蝶梦魂',
    'lvup' => 37,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '庄生晓梦迷蝴蝶，望帝春心托杜鹃',
    'type' => 3,
    'icon' => 'body_0_37',
    'unlock' => 3,
    'lvup2' => 37,
    'cardSlot' => 37,
    'storyname1' => '蝶衣·一',
    'story1' => '紫色的凤蝶在黑夜中飞舞，翅膀流转着月光，散落五彩的鳞粉，带人入梦。',
    'unlocktype1' => 1,
    'para1' => 337,
    'storyname2' => '蝶衣·二',
    'story2' => '沉睡的人们会梦到心中最挂念之事，或是远方的亲友，或是曾经的遗憾。',
    'unlocktype2' => 1,
    'para2' => 237,
    'storyname3' => '蝶衣·三',
    'story3' => '凤蝶穿行在梦中，那梦里各种各样的感情让它的鳞翅愈发艳丽。而它却只是梦境的过客。',
    'unlocktype3' => 1,
    'para3' => 37,
    'storyname4' => '蝶衣·四',
    'story4' => '它偶尔也会为一两个梦境驻足，随后挥动翅膀将它带走，留做梦之人一个安眠。',
    'unlocktype4' => 2,
    'para4' => 5,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  38 => 
  array (
    'id' => 38,
    'clother' => 
    array (
      0 => 38,
      1 => 238,
    ),
    'name' => '微步生尘',
    'lvup' => 38,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '东风正有去年花，柔条去做谁家柳',
    'type' => 2,
    'icon' => 'body_0_38',
    'unlock' => 3,
    'lvup2' => 38,
    'cardSlot' => 38,
    'storyname1' => '莲纹',
    'story1' => '自前朝起，不论民间还是官家都喜以莲花作为装饰，以彰显吉祥纯洁的愿望。',
    'unlocktype1' => 1,
    'para1' => 238,
    'storyname2' => '莲冠',
    'story2' => '身份尊贵的官家女子将发冠打造成莲花形状，再缀以飘逸发带，便显得整个人飘然欲仙。',
    'unlocktype2' => 1,
    'para2' => 38,
    'storyname3' => '无尘花',
    'story3' => '前朝还有传说，仙界有一种与白莲共生的花，名曰无尘。无尘花白而泛青，玲珑剔透，不染凡尘。',
    'unlocktype3' => 2,
    'para3' => 5,
    'storyname4' => '共生',
    'story4' => '民间将“无尘”按传说所言绘出，并与莲花一起用做装饰，盼望属于天界的花儿为自己带来好运。',
    'unlocktype4' => 2,
    'para4' => 10,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  39 => 
  array (
    'id' => 39,
    'clother' => 
    array (
      0 => 39,
      1 => 239,
    ),
    'name' => '广陵嫁衣',
    'lvup' => 39,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '宜言饮酒，与子偕老。琴瑟在御，莫不静好。',
    'type' => 3,
    'icon' => 'body_0_39',
    'unlock' => 3,
    'lvup2' => 39,
    'cardSlot' => 39,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  40 => 
  array (
    'id' => 40,
    'clother' => 
    array (
      0 => 40,
      1 => 240,
      2 => 340,
    ),
    'name' => '平沙落雁',
    'lvup' => 40,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '鸿雁来也楚江空，碧云天净。长空一色，万里动微茫，江涵秋影。',
    'type' => 2,
    'icon' => 'body_0_40',
    'unlock' => 3,
    'lvup2' => 40,
    'cardSlot' => 40,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  41 => 
  array (
    'id' => 41,
    'clother' => 
    array (
      0 => 41,
      1 => 241,
      2 => 341,
    ),
    'name' => '寒花微云',
    'lvup' => 41,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '舒卷意何穷，萦流复带空',
    'type' => 2,
    'icon' => 'body_0_41',
    'unlock' => 3,
    'lvup2' => 41,
    'cardSlot' => 41,
    'storyname1' => '烟雨',
    'story1' => '早春时节，烟雨连绵，蒙着淡青色雨雾的小城之中，随处可见淡青色的纸伞。',
    'unlocktype1' => 1,
    'para1' => 341,
    'storyname2' => '寒花',
    'story2' => '春寒料峭，却有花无声开放。寒花在春雨中飘落，些许落在游人青色的纸伞上。',
    'unlocktype2' => 1,
    'para2' => 41,
    'storyname3' => '微云',
    'story3' => '这朦胧烟雨、青山绿水，常被丹青客入画。而晕染开的画卷，也常常为织局布庄提供灵感。',
    'unlocktype3' => 1,
    'para3' => 41,
    'storyname4' => '落魄人',
    'story4' => '他空有一腔抱负，来到繁华江南，只为成为出名的画师。只可惜他从大漠沙画到江南春，却没有一副画成名。',
    'unlocktype4' => 2,
    'para4' => 5,
    'storyname5' => '纹样师',
    'story5' => '起初注意到他的是素锦布庄，请他为新的布料绘制纹样。一来二去，他竟成了全江南最受欢迎的纹样师。',
    'unlocktype5' => 2,
    'para5' => 10,
  ),
  42 => 
  array (
    'id' => 42,
    'clother' => 
    array (
      0 => 42,
      1 => 242,
      2 => 342,
    ),
    'name' => '三途引渡',
    'lvup' => 42,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '坠入彼岸之梦的魂灵，随着魂灯的牵引，才能渡过三途河',
    'type' => 4,
    'icon' => 'body_0_42',
    'unlock' => 3,
    'lvup2' => 42,
    'cardSlot' => 42,
    'storyname1' => '三途',
    'story1' => '凡人死后，魂灵会穿过一条名为三途的河流。',
    'unlocktype1' => 1,
    'para1' => 342,
    'storyname2' => '魂灯',
    'story2' => '三途河上迷雾遍布，若无魂灯指引，便会很快迷失在迷雾之中，迷失在彼岸花编织的梦境之中。',
    'unlocktype2' => 1,
    'para2' => 242,
    'storyname3' => '引路人·一',
    'story3' => '相传三途河上有位提着魂灯的红衣引路人，千百年都在那里，日复一日，年复一年，往返在三途河上。',
    'unlocktype3' => 1,
    'para3' => 42,
    'storyname4' => '引路人·二',
    'story4' => '直到某天，一名孩童来到这里。引路人古井无波的眼眸终于流动了起来，她将魂灯插在船头，牵着孩童的手下了船。',
    'unlocktype4' => 2,
    'para4' => 5,
    'storyname5' => '引路人·三',
    'story5' => '那红衣的引路人从此便消失了，可那盏魂灯却仍未熄灭——地府之中，又怎会缺心有执念、徘徊不愿离去的人呢？',
    'unlocktype5' => 2,
    'para5' => 10,
  ),
  43 => 
  array (
    'id' => 43,
    'clother' => 
    array (
      0 => 43,
      1 => 243,
      2 => 343,
    ),
    'name' => '越鸟南飞',
    'lvup' => 43,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '觉来欲往心悠然，魂随越鸟飞南天',
    'type' => 1,
    'icon' => 'body_0_43',
    'unlock' => 3,
    'lvup2' => 43,
    'cardSlot' => 43,
    'storyname1' => '越鸟·一',
    'story1' => '南方有鸟，其羽熠熠，谓之越鸟，又名孔雀。',
    'unlocktype1' => 1,
    'para1' => 243,
    'storyname2' => '越鸟·二',
    'story2' => '长安城中的富商豢养了几只孔雀，其中一只颜色素白如雪，没有一丝杂色。',
    'unlocktype2' => 1,
    'para2' => 43,
    'storyname3' => '越鸟·三',
    'story3' => '白色孔雀一事在京城传开，不少人慕名而来，想要一睹真容。富商便将孔雀关入笼中，只要付钱便能观赏。',
    'unlocktype3' => 2,
    'para3' => 5,
    'storyname4' => '越鸟·五',
    'story4' => '某夜电闪雷鸣，风雨交加，商人在睡梦中听到一声清越鸟鸣。他连忙披衣出门，只看到一只白鸟向南飞去。',
    'unlocktype4' => 2,
    'para4' => 10,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  44 => 
  array (
    'id' => 44,
    'clother' => 
    array (
      0 => 44,
      1 => 244,
    ),
    'name' => '蟾宫桂子',
    'lvup' => 44,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '记蟾宫桂子，洒向人间，如今时候。',
    'type' => 1,
    'icon' => 'body_0_44',
    'unlock' => 3,
    'lvup2' => 44,
    'cardSlot' => 44,
    'storyname1' => '蟾宫·一',
    'story1' => '每年中秋，天子都会在上林苑的拜月台前大宴群臣。',
    'unlocktype1' => 1,
    'para1' => 244,
    'storyname2' => '蟾宫·二',
    'story2' => '待到月亮升起，一名舞姬便会穿着隆重华贵的衣裙，在拜月台上翩翩起舞。',
    'unlocktype2' => 1,
    'para2' => 44,
    'storyname3' => '蟾宫·三',
    'story3' => '银月将曼妙的影子投射下来，仿佛仙子降临人间。',
    'unlocktype3' => 2,
    'para3' => 5,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  45 => 
  array (
    'id' => 45,
    'clother' => 
    array (
      0 => 45,
      1 => 245,
      2 => 345,
    ),
    'name' => '星罗万象',
    'lvup' => 45,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '她从神秘的远方走来，衣裙映着星辰与明月的辉光',
    'type' => 4,
    'icon' => 'body_0_45',
    'unlock' => 3,
    'lvup2' => 45,
    'cardSlot' => 45,
    'storyname1' => '繁星·一',
    'story1' => '她从神秘的荒原走来，衣裙上映着繁星的光辉。',
    'unlocktype1' => 1,
    'para1' => 345,
    'storyname2' => '繁星·二',
    'story2' => '传闻她的双眸能解读星辰运转，却从不肯告诉世人。',
    'unlocktype2' => 1,
    'para2' => 245,
    'storyname3' => '繁星·三',
    'story3' => '无人知晓她来自何方，唯有星辰和残月歌颂她的名字。',
    'unlocktype3' => 1,
    'para3' => 45,
    'storyname4' => '繁星·四',
    'story4' => '她悄无声息地消失在世间，只留下了一本书，据说上面用星辰的尘埃书写着未来。',
    'unlocktype4' => 2,
    'para4' => 5,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  46 => 
  array (
    'id' => 46,
    'clother' => 
    array (
      0 => 46,
      1 => 246,
      2 => 346,
    ),
    'name' => '沙场点兵',
    'lvup' => 46,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '一身飒爽的红，是她纵横沙场数年独有的颜色',
    'type' => 2,
    'icon' => 'body_0_46',
    'unlock' => 3,
    'lvup2' => 46,
    'cardSlot' => 46,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  47 => 
  array (
    'id' => 47,
    'clother' => 
    array (
      0 => 47,
      1 => 247,
      2 => 347,
    ),
    'name' => '朔雪胡风',
    'lvup' => 47,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '她穿着白色的猎装，披风就像一团火，卷携着原野上的风',
    'type' => 2,
    'icon' => 'body_0_47',
    'unlock' => 3,
    'lvup2' => 47,
    'cardSlot' => 47,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  48 => 
  array (
    'id' => 48,
    'clother' => 
    array (
      0 => 48,
      1 => 248,
      2 => 348,
    ),
    'name' => '落叶秋枫',
    'lvup' => 48,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => '风吹红叶浮水中，梢头红叶水底映，一池深浅红',
    'type' => 4,
    'icon' => 'body_0_48',
    'unlock' => 3,
    'lvup2' => 48,
    'cardSlot' => 48,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  53 => 
  array (
    'id' => 53,
    'clother' => 
    array (
      0 => 53,
      1 => 253,
      2 => 353,
    ),
    'name' => '天竺法音',
    'lvup' => 53,
    'show_time' => '2019-08-07 00:00:00',
    'show_avid' => 6500,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 4,
    'icon' => 'body_0_53',
    'unlock' => 3,
    'lvup2' => 53,
    'cardSlot' => 53,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1002 => 
  array (
    'id' => 1002,
    'clother' => 
    array (
      0 => 1002,
      1 => 1202,
      2 => 302,
    ),
    'name' => '山中有灵',
    'lvup' => 1002,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 3,
    'icon' => 'body_0_4',
    'unlock' => 1,
    'lvup2' => 1002,
    'cardSlot' => 1002,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1003 => 
  array (
    'id' => 1003,
    'clother' => 
    array (
      0 => 1003,
      1 => 1203,
      2 => 303,
    ),
    'name' => '杏园撷芳',
    'lvup' => 1003,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 3,
    'icon' => 'body_0_5',
    'unlock' => 1,
    'lvup2' => 1003,
    'cardSlot' => 1003,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1004 => 
  array (
    'id' => 1004,
    'clother' => 
    array (
      0 => 1004,
      1 => 1204,
      2 => 304,
    ),
    'name' => '兰之猗猗',
    'lvup' => 1004,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 3,
    'icon' => 'body_0_19',
    'unlock' => 1,
    'lvup2' => 1004,
    'cardSlot' => 1004,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1005 => 
  array (
    'id' => 1005,
    'clother' => 
    array (
      0 => 1005,
      1 => 1205,
    ),
    'name' => '大吕服',
    'lvup' => 1005,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着大吕御史身份的官服。',
    'type' => 1,
    'icon' => 'body_0_6',
    'unlock' => 1,
    'lvup2' => 1005,
    'cardSlot' => 1005,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1006 => 
  array (
    'id' => 1006,
    'clother' => 
    array (
      0 => 1006,
      1 => 1206,
    ),
    'name' => '锦绣霓裳',
    'lvup' => 1006,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 1,
    'icon' => 'body_0_8',
    'unlock' => 1,
    'lvup2' => 1006,
    'cardSlot' => 1006,
    'storyname1' => '桃花锦·一',
    'story1' => '制造局新出了一批布料，其纹样却并非宫中画师所绘，而是请民间小有盛名的吉祥布庄绘制，将其命名为桃花锦。',
    'unlocktype1' => 1,
    'para1' => 1206,
    'storyname2' => '桃花锦·二',
    'story2' => '宫中几位妃嫔听闻此事，都觉穿着民间绘师所设计之布有辱身份，因此这批布料被连夜改制为女官官服。',
    'unlocktype2' => 1,
    'para2' => 1006,
    'storyname3' => '桃花锦·三',
    'story3' => '谁知这做出来的衣服轻盈若仙子、灿然如桃花，花纹更是灵动非常，宫中一时桃花盛放，美不胜收。',
    'unlocktype3' => 1,
    'para3' => 1006,
    'storyname4' => '桃花锦·四',
    'story4' => '后宫妃嫔一时都懊悔不已，只得弹劾女官衣着艳丽不甚庄重，这弹劾的奏章则尽数被御史大夫压在了兰台的桌脚下。',
    'unlocktype4' => 2,
    'para4' => 5,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1007 => 
  array (
    'id' => 1007,
    'clother' => 
    array (
      0 => 1007,
      1 => 1207,
      2 => 307,
    ),
    'name' => '紫薇花露',
    'lvup' => 1007,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 1,
    'icon' => 'body_0_7',
    'unlock' => 1,
    'lvup2' => 1007,
    'cardSlot' => 1007,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1008 => 
  array (
    'id' => 1008,
    'clother' => 
    array (
      0 => 1008,
      1 => 1208,
      2 => 308,
    ),
    'name' => '太微辞',
    'lvup' => 1008,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 2,
    'icon' => 'body_0_9',
    'unlock' => 1,
    'lvup2' => 1008,
    'cardSlot' => 1008,
    'storyname1' => '太微·一',
    'story1' => '太微之服实则为前朝慧太妃设计。太妃深居简出，对佛法禅道颇有研究，十数年来帮助天禄阁补全佛法数本。',
    'unlocktype1' => 1,
    'para1' => 1208,
    'storyname2' => '太微·二',
    'story2' => '慧太妃生性淡泊，将渊帝送来的、据说一匹千金的神素锦裁剪成礼服，赠予当时德高望重的仲吕女官。',
    'unlocktype2' => 1,
    'para2' => 1008,
    'storyname3' => '太微·三',
    'story3' => '慧太妃故去不久，那女官也病逝而去，而最初的那套太微之服则存放在慧太妃的陵寝之中。',
    'unlocktype3' => 1,
    'para3' => 1008,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1009 => 
  array (
    'id' => 1009,
    'clother' => 
    array (
      0 => 1009,
      1 => 1209,
    ),
    'name' => '幽兰调',
    'lvup' => 1009,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 1,
    'icon' => 'body_0_10',
    'unlock' => 1,
    'lvup2' => 1009,
    'cardSlot' => 1009,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1010 => 
  array (
    'id' => 1010,
    'clother' => 
    array (
      0 => 1010,
      1 => 1210,
      2 => 310,
    ),
    'name' => '黄钟服',
    'lvup' => 1010,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => '象征着黄钟御史身份的官服。',
    'type' => 1,
    'icon' => 'body_0_11',
    'unlock' => 2,
    'lvup2' => 1010,
    'cardSlot' => 1010,
    'storyname1' => NULL,
    'story1' => NULL,
    'unlocktype1' => NULL,
    'para1' => NULL,
    'storyname2' => NULL,
    'story2' => NULL,
    'unlocktype2' => NULL,
    'para2' => NULL,
    'storyname3' => NULL,
    'story3' => NULL,
    'unlocktype3' => NULL,
    'para3' => NULL,
    'storyname4' => NULL,
    'story4' => NULL,
    'unlocktype4' => NULL,
    'para4' => NULL,
    'storyname5' => NULL,
    'story5' => NULL,
    'unlocktype5' => NULL,
    'para5' => NULL,
  ),
  1011 => 
  array (
    'id' => 1011,
    'clother' => 
    array (
      0 => 1011,
      1 => 1211,
      2 => 311,
    ),
    'name' => '沧海龙吟',
    'lvup' => 1011,
    'show_time' => '2001-09-15 08:00:00',
    'show_avid' => 81,
    'ep' => 
    array (
    ),
    'des' => NULL,
    'type' => 1,
    'icon' => 'body_0_17',
    'unlock' => 2,
    'lvup2' => 1011,
    'cardSlot' => 1011,
    'storyname1' => '摄政御史',
    'story1' => '御史大夫虽有协理朝政之权，可古往今来能够达到摄政御史的女官也仅有两人。',
    'unlocktype1' => 1,
    'para1' => 311,
    'storyname2' => '龙吟之冠',
    'story2' => '以精铜打造成青鸟形状，上镶嵌云翠石数颗，坠有南海珍珠，极尽华丽。',
    'unlocktype2' => 1,
    'para2' => 1211,
    'storyname3' => '龙吟之服',
    'story3' => '摄政御史之服所用布匹材质可比太子，流光溢彩亦不失威严，上面绣有象征辅佐天子的蛟龙暗纹。',
    'unlocktype3' => 1,
    'para3' => 1011,
    'storyname4' => '龙纹',
    'story4' => '关于摄政御史衣服上采用蛟龙暗纹一事，朝中群臣起初反对之声颇高。高祖皇帝力排众议，执意保留其形制。',
    'unlocktype4' => 2,
    'para4' => 5,
    'storyname5' => '四海升平',
    'story5' => '自那之后，朝中任命的摄政御史都没有辜负高祖皇帝的期望，民间因此有一传闻——蛟龙出，四海升平。',
    'unlocktype5' => 2,
    'para5' => 10,
  ),
);