<?php
//特殊关卡
return array (
  'huiyao10' => 
  array (
    'id' => 'huiyao10',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 1,
    'unlock' => 1000,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'nangongchen12' => 
  array (
    'id' => 'nangongchen12',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 1,
    'unlock' => 1000,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'linchengan14' => 
  array (
    'id' => 'linchengan14',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 1,
    'unlock' => 1000,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'xiaoyi12' => 
  array (
    'id' => 'xiaoyi12',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 1,
    'unlock' => 1000,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'huiyao2' => 
  array (
    'id' => 'huiyao2',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'nangongchen1' => 
  array (
    'id' => 'nangongchen1',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'nangongchen13' => 
  array (
    'id' => 'nangongchen13',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 3,
    'unlock' => 310,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'nangongchen2' => 
  array (
    'id' => 'nangongchen2',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'linchengan17' => 
  array (
    'id' => 'linchengan17',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 3,
    'unlock' => 80,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'linchengan2' => 
  array (
    'id' => 'linchengan2',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'linchengan7' => 
  array (
    'id' => 'linchengan7',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 3,
    'unlock' => 822,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'xiaoyizx1' => 
  array (
    'id' => 'xiaoyizx1',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'xiaoyi2' => 
  array (
    'id' => 'xiaoyi2',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'xiaoyi3' => 
  array (
    'id' => 'xiaoyi3',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'weiji1' => 
  array (
    'id' => 'weiji1',
    'type' => 1,
    'roleid' => 5,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'huiyao1' => 
  array (
    'id' => 'huiyao1',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'huiyao6' => 
  array (
    'id' => 'huiyao6',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'huiyao7' => 
  array (
    'id' => 'huiyao7',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'huiyao8' => 
  array (
    'id' => 'huiyao8',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'huiyao9' => 
  array (
    'id' => 'huiyao9',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 3,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'huiyao11' => 
  array (
    'id' => 'huiyao11',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 2,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'nangongchen4' => 
  array (
    'id' => 'nangongchen4',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 0,
    'specMsg' => 0,
    'color' => 0,
    'voice' => 0,
    'tree' => 0,
  ),
  'nangongchen3' => 
  array (
    'id' => 'nangongchen3',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 3,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'nangongchen7' => 
  array (
    'id' => 'nangongchen7',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'nangongchen8' => 
  array (
    'id' => 'nangongchen8',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'nangongchen9' => 
  array (
    'id' => 'nangongchen9',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'nangongchen10' => 
  array (
    'id' => 'nangongchen10',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'nangongchen11' => 
  array (
    'id' => 'nangongchen11',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'linchengan8' => 
  array (
    'id' => 'linchengan8',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 1,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'linchengan9' => 
  array (
    'id' => 'linchengan9',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 1,
    'color' => 5,
    'voice' => 1,
    'tree' => 1,
  ),
  'linchengan10' => 
  array (
    'id' => 'linchengan10',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'linchengan11' => 
  array (
    'id' => 'linchengan11',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 3,
    'specMsg' => 2,
    'color' => 5,
    'voice' => 1,
    'tree' => 1,
  ),
  'linchengan12' => 
  array (
    'id' => 'linchengan12',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 4,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'linchengan13' => 
  array (
    'id' => 'linchengan13',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'linchengan15' => 
  array (
    'id' => 'linchengan15',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'linchengan16' => 
  array (
    'id' => 'linchengan16',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 4,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'xiaoyi7' => 
  array (
    'id' => 'xiaoyi7',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 3,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'xiaoyi8' => 
  array (
    'id' => 'xiaoyi8',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 3,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'xiaoyi9' => 
  array (
    'id' => 'xiaoyi9',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'xiaoyi10' => 
  array (
    'id' => 'xiaoyi10',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'xiaoyi11' => 
  array (
    'id' => 'xiaoyi11',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 1,
    'specMsg' => 2,
    'color' => 3,
    'voice' => 0,
    'tree' => 1,
  ),
  'xiaoyi13' => 
  array (
    'id' => 'xiaoyi13',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 4,
    'unlock' => 0,
    'star' => 2,
    'specMsg' => 1,
    'color' => 4,
    'voice' => 0,
    'tree' => 1,
  ),
  'huiyao3' => 
  array (
    'id' => 'huiyao3',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'huiyao4' => 
  array (
    'id' => 'huiyao4',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'huiyao5' => 
  array (
    'id' => 'huiyao5',
    'type' => 1,
    'roleid' => 1,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'nangongchen5' => 
  array (
    'id' => 'nangongchen5',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'nangongchen6' => 
  array (
    'id' => 'nangongchen6',
    'type' => 1,
    'roleid' => 2,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'linchengan3' => 
  array (
    'id' => 'linchengan3',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'linchengan4' => 
  array (
    'id' => 'linchengan4',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'linchengan5' => 
  array (
    'id' => 'linchengan5',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'linchengan6' => 
  array (
    'id' => 'linchengan6',
    'type' => 1,
    'roleid' => 3,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'xiaoyi4' => 
  array (
    'id' => 'xiaoyi4',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'xiaoyi5' => 
  array (
    'id' => 'xiaoyi5',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'xiaoyi6' => 
  array (
    'id' => 'xiaoyi6',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'xiaoyi14' => 
  array (
    'id' => 'xiaoyi14',
    'type' => 1,
    'roleid' => 4,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiyan1' => 
  array (
    'id' => 'jiyan1',
    'type' => 1,
    'roleid' => 6,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'jiyan2' => 
  array (
    'id' => 'jiyan2',
    'type' => 1,
    'roleid' => 6,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'weiji2' => 
  array (
    'id' => 'weiji2',
    'type' => 1,
    'roleid' => 5,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
  'weiji3' => 
  array (
    'id' => 'weiji3',
    'type' => 1,
    'roleid' => 5,
    'unlocktype' => 10,
    'unlock' => 0,
    'star' => 7,
    'specMsg' => 0,
    'color' => 4,
    'voice' => 0,
    'tree' => 0,
  ),
);