<?php
//郊游-获得道具
return array (
  1 => 
  array (
    1 => 
    array (
      'id' => 1,
      'heroType' => 1,
      'stageCondition' => 1,
      'item' => 10,
      'initWeight' => 50,
      'refreshWeight' => 50,
      'output' => 0,
      'baseNum' => 20,
      'kind' => 1,
    ),
    2 => 
    array (
      'id' => 2,
      'heroType' => 1,
      'stageCondition' => 1,
      'item' => 6007,
      'initWeight' => 4,
      'refreshWeight' => 8,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    3 => 
    array (
      'id' => 3,
      'heroType' => 1,
      'stageCondition' => 5,
      'item' => 6001,
      'initWeight' => 3,
      'refreshWeight' => 6,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    4 => 
    array (
      'id' => 4,
      'heroType' => 1,
      'stageCondition' => 10,
      'item' => 6002,
      'initWeight' => 2,
      'refreshWeight' => 4,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    5 => 
    array (
      'id' => 5,
      'heroType' => 1,
      'stageCondition' => 15,
      'item' => 5996,
      'initWeight' => 5,
      'refreshWeight' => 10,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 1,
    ),
    6 => 
    array (
      'id' => 6,
      'heroType' => 1,
      'stageCondition' => 1,
      'item' => 5003,
      'initWeight' => 40,
      'refreshWeight' => 40,
      'output' => 0,
      'baseNum' => 7,
      'kind' => 1,
    ),
    7 => 
    array (
      'id' => 7,
      'heroType' => 1,
      'stageCondition' => 1,
      'item' => 807,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 2,
      'kind' => 1,
    ),
    8 => 
    array (
      'id' => 8,
      'heroType' => 1,
      'stageCondition' => 10,
      'item' => 801,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 3,
      'kind' => 1,
    ),
    9 => 
    array (
      'id' => 9,
      'heroType' => 1,
      'stageCondition' => 1,
      'item' => 6033,
      'initWeight' => 5,
      'refreshWeight' => 5,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
  ),
  2 => 
  array (
    10 => 
    array (
      'id' => 10,
      'heroType' => 2,
      'stageCondition' => 1,
      'item' => 10,
      'initWeight' => 50,
      'refreshWeight' => 50,
      'output' => 0,
      'baseNum' => 20,
      'kind' => 1,
    ),
    11 => 
    array (
      'id' => 11,
      'heroType' => 2,
      'stageCondition' => 1,
      'item' => 6007,
      'initWeight' => 4,
      'refreshWeight' => 8,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    12 => 
    array (
      'id' => 12,
      'heroType' => 2,
      'stageCondition' => 5,
      'item' => 6001,
      'initWeight' => 3,
      'refreshWeight' => 6,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    13 => 
    array (
      'id' => 13,
      'heroType' => 2,
      'stageCondition' => 10,
      'item' => 6002,
      'initWeight' => 2,
      'refreshWeight' => 4,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    14 => 
    array (
      'id' => 14,
      'heroType' => 2,
      'stageCondition' => 15,
      'item' => 5996,
      'initWeight' => 5,
      'refreshWeight' => 10,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 1,
    ),
    15 => 
    array (
      'id' => 15,
      'heroType' => 2,
      'stageCondition' => 1,
      'item' => 5003,
      'initWeight' => 40,
      'refreshWeight' => 40,
      'output' => 0,
      'baseNum' => 7,
      'kind' => 1,
    ),
    16 => 
    array (
      'id' => 16,
      'heroType' => 2,
      'stageCondition' => 1,
      'item' => 807,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 2,
      'kind' => 1,
    ),
    17 => 
    array (
      'id' => 17,
      'heroType' => 2,
      'stageCondition' => 10,
      'item' => 802,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 3,
      'kind' => 1,
    ),
    18 => 
    array (
      'id' => 18,
      'heroType' => 2,
      'stageCondition' => 1,
      'item' => 6032,
      'initWeight' => 5,
      'refreshWeight' => 5,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
  ),
  3 => 
  array (
    19 => 
    array (
      'id' => 19,
      'heroType' => 3,
      'stageCondition' => 1,
      'item' => 10,
      'initWeight' => 50,
      'refreshWeight' => 50,
      'output' => 0,
      'baseNum' => 20,
      'kind' => 1,
    ),
    20 => 
    array (
      'id' => 20,
      'heroType' => 3,
      'stageCondition' => 1,
      'item' => 6007,
      'initWeight' => 4,
      'refreshWeight' => 8,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    21 => 
    array (
      'id' => 21,
      'heroType' => 3,
      'stageCondition' => 5,
      'item' => 6001,
      'initWeight' => 3,
      'refreshWeight' => 6,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    22 => 
    array (
      'id' => 22,
      'heroType' => 3,
      'stageCondition' => 10,
      'item' => 6002,
      'initWeight' => 2,
      'refreshWeight' => 4,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    23 => 
    array (
      'id' => 23,
      'heroType' => 3,
      'stageCondition' => 15,
      'item' => 5996,
      'initWeight' => 5,
      'refreshWeight' => 10,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 1,
    ),
    24 => 
    array (
      'id' => 24,
      'heroType' => 3,
      'stageCondition' => 1,
      'item' => 5003,
      'initWeight' => 40,
      'refreshWeight' => 40,
      'output' => 0,
      'baseNum' => 7,
      'kind' => 1,
    ),
    25 => 
    array (
      'id' => 25,
      'heroType' => 3,
      'stageCondition' => 1,
      'item' => 807,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 2,
      'kind' => 1,
    ),
    26 => 
    array (
      'id' => 26,
      'heroType' => 3,
      'stageCondition' => 10,
      'item' => 803,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 3,
      'kind' => 1,
    ),
    27 => 
    array (
      'id' => 27,
      'heroType' => 3,
      'stageCondition' => 1,
      'item' => 6034,
      'initWeight' => 5,
      'refreshWeight' => 5,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
  ),
  4 => 
  array (
    28 => 
    array (
      'id' => 28,
      'heroType' => 4,
      'stageCondition' => 1,
      'item' => 10,
      'initWeight' => 50,
      'refreshWeight' => 50,
      'output' => 0,
      'baseNum' => 20,
      'kind' => 1,
    ),
    29 => 
    array (
      'id' => 29,
      'heroType' => 4,
      'stageCondition' => 1,
      'item' => 6007,
      'initWeight' => 4,
      'refreshWeight' => 8,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    30 => 
    array (
      'id' => 30,
      'heroType' => 4,
      'stageCondition' => 5,
      'item' => 6001,
      'initWeight' => 3,
      'refreshWeight' => 6,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    31 => 
    array (
      'id' => 31,
      'heroType' => 4,
      'stageCondition' => 10,
      'item' => 6002,
      'initWeight' => 2,
      'refreshWeight' => 4,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    32 => 
    array (
      'id' => 32,
      'heroType' => 4,
      'stageCondition' => 15,
      'item' => 5996,
      'initWeight' => 5,
      'refreshWeight' => 10,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 1,
    ),
    33 => 
    array (
      'id' => 33,
      'heroType' => 4,
      'stageCondition' => 1,
      'item' => 5003,
      'initWeight' => 40,
      'refreshWeight' => 40,
      'output' => 0,
      'baseNum' => 7,
      'kind' => 1,
    ),
    34 => 
    array (
      'id' => 34,
      'heroType' => 4,
      'stageCondition' => 1,
      'item' => 807,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 2,
      'kind' => 1,
    ),
    35 => 
    array (
      'id' => 35,
      'heroType' => 4,
      'stageCondition' => 10,
      'item' => 804,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 3,
      'kind' => 1,
    ),
    36 => 
    array (
      'id' => 36,
      'heroType' => 4,
      'stageCondition' => 1,
      'item' => 6042,
      'initWeight' => 5,
      'refreshWeight' => 5,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
  ),
  5 => 
  array (
    37 => 
    array (
      'id' => 37,
      'heroType' => 5,
      'stageCondition' => 1,
      'item' => 10,
      'initWeight' => 50,
      'refreshWeight' => 50,
      'output' => 0,
      'baseNum' => 20,
      'kind' => 1,
    ),
    38 => 
    array (
      'id' => 38,
      'heroType' => 5,
      'stageCondition' => 1,
      'item' => 6007,
      'initWeight' => 4,
      'refreshWeight' => 8,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    39 => 
    array (
      'id' => 39,
      'heroType' => 5,
      'stageCondition' => 5,
      'item' => 6001,
      'initWeight' => 3,
      'refreshWeight' => 6,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    40 => 
    array (
      'id' => 40,
      'heroType' => 5,
      'stageCondition' => 10,
      'item' => 6002,
      'initWeight' => 2,
      'refreshWeight' => 4,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    41 => 
    array (
      'id' => 41,
      'heroType' => 5,
      'stageCondition' => 15,
      'item' => 5996,
      'initWeight' => 5,
      'refreshWeight' => 10,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 1,
    ),
    42 => 
    array (
      'id' => 42,
      'heroType' => 5,
      'stageCondition' => 1,
      'item' => 5003,
      'initWeight' => 40,
      'refreshWeight' => 40,
      'output' => 0,
      'baseNum' => 7,
      'kind' => 1,
    ),
    43 => 
    array (
      'id' => 43,
      'heroType' => 5,
      'stageCondition' => 1,
      'item' => 807,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 2,
      'kind' => 1,
    ),
    44 => 
    array (
      'id' => 44,
      'heroType' => 5,
      'stageCondition' => 10,
      'item' => 805,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 3,
      'kind' => 1,
    ),
    45 => 
    array (
      'id' => 45,
      'heroType' => 5,
      'stageCondition' => 1,
      'item' => 6043,
      'initWeight' => 5,
      'refreshWeight' => 5,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
  ),
  6 => 
  array (
    46 => 
    array (
      'id' => 46,
      'heroType' => 6,
      'stageCondition' => 1,
      'item' => 10,
      'initWeight' => 50,
      'refreshWeight' => 50,
      'output' => 0,
      'baseNum' => 20,
      'kind' => 1,
    ),
    47 => 
    array (
      'id' => 47,
      'heroType' => 6,
      'stageCondition' => 1,
      'item' => 6007,
      'initWeight' => 4,
      'refreshWeight' => 8,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    48 => 
    array (
      'id' => 48,
      'heroType' => 6,
      'stageCondition' => 5,
      'item' => 6001,
      'initWeight' => 3,
      'refreshWeight' => 6,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    49 => 
    array (
      'id' => 49,
      'heroType' => 6,
      'stageCondition' => 10,
      'item' => 6002,
      'initWeight' => 2,
      'refreshWeight' => 4,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
    50 => 
    array (
      'id' => 50,
      'heroType' => 6,
      'stageCondition' => 15,
      'item' => 5996,
      'initWeight' => 5,
      'refreshWeight' => 10,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 1,
    ),
    51 => 
    array (
      'id' => 51,
      'heroType' => 6,
      'stageCondition' => 1,
      'item' => 5003,
      'initWeight' => 40,
      'refreshWeight' => 40,
      'output' => 0,
      'baseNum' => 7,
      'kind' => 1,
    ),
    52 => 
    array (
      'id' => 52,
      'heroType' => 6,
      'stageCondition' => 1,
      'item' => 807,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 2,
      'kind' => 1,
    ),
    53 => 
    array (
      'id' => 53,
      'heroType' => 6,
      'stageCondition' => 10,
      'item' => 806,
      'initWeight' => 30,
      'refreshWeight' => 50,
      'output' => 1,
      'baseNum' => 3,
      'kind' => 1,
    ),
    54 => 
    array (
      'id' => 54,
      'heroType' => 6,
      'stageCondition' => 1,
      'item' => 6044,
      'initWeight' => 5,
      'refreshWeight' => 5,
      'output' => 1,
      'baseNum' => 1,
      'kind' => 106,
    ),
  ),
);