<?php
//贵人令-任务
return array (
  1 => 
  array (
    'id' => 1,
    'name' => '每日政务',
    'name_cn' => '每日完成政务X次',
    'awardexp' => 15,
    'type' => 1,
    'need' => 1,
    'info' => '每日完成政务1次',
    'info_cn' => '每日完成政务1次',
    'use' => 17,
    'tasktype' => 117,
    'is_show' => 1,
    'icon' => 1,
  ),
  2 => 
  array (
    'id' => 2,
    'name' => '每日行商',
    'name_cn' => '每日完成行商X次',
    'awardexp' => 15,
    'type' => 1,
    'need' => 1,
    'info' => '每日完成行商1次',
    'info_cn' => '每日完成行商1次',
    'use' => 16,
    'tasktype' => 12,
    'is_show' => 1,
    'icon' => 1,
  ),
  3 => 
  array (
    'id' => 3,
    'name' => '每日赴约',
    'name_cn' => '每日完成赴约X次',
    'awardexp' => 15,
    'type' => 1,
    'need' => 1,
    'info' => '每日完成赴约1次',
    'info_cn' => '每日完成赴约1次',
    'use' => 135,
    'tasktype' => 148,
    'is_show' => 1,
    'icon' => 1,
  ),
  4 => 
  array (
    'id' => 4,
    'name' => '每日许愿（心动时刻）',
    'name_cn' => '每日许愿（心动时刻）X次',
    'awardexp' => 20,
    'type' => 1,
    'need' => 1,
    'info' => '每日许愿（心动时刻）1次',
    'info_cn' => '每日许愿（心动时刻）1次',
    'use' => 121,
    'tasktype' => 112,
    'is_show' => 1,
    'icon' => 1,
  ),
  5 => 
  array (
    'id' => 5,
    'name' => '每日许愿（四海奇珍）',
    'name_cn' => '每日许愿（四海奇珍）X次',
    'awardexp' => 20,
    'type' => 1,
    'need' => 1,
    'info' => '每日许愿（四海奇珍）1次',
    'info_cn' => '每日许愿（四海奇珍）1次',
    'use' => 122,
    'tasktype' => 111,
    'is_show' => 1,
    'icon' => 1,
  ),
  6 => 
  array (
    'id' => 6,
    'name' => '每日献礼',
    'name_cn' => '每日郊祀献礼X次',
    'awardexp' => 20,
    'type' => 1,
    'need' => 1,
    'info' => '每日郊祀献礼1次',
    'info_cn' => '每日郊祀献礼1次',
    'use' => 30,
    'tasktype' => 139,
    'is_show' => 1,
    'icon' => 1,
  ),
  7 => 
  array (
    'id' => 7,
    'name' => '每日问候',
    'name_cn' => '每日问候次数',
    'awardexp' => 10,
    'type' => 1,
    'need' => 1,
    'info' => '每日问候1次',
    'info_cn' => '每日问候1次',
    'use' => 15,
    'tasktype' => 17,
    'is_show' => 1,
    'icon' => 1,
  ),
  8 => 
  array (
    'id' => 8,
    'name' => '每日出游',
    'name_cn' => '每日出游次数',
    'awardexp' => 10,
    'type' => 1,
    'need' => 1,
    'info' => '每日出游1次',
    'info_cn' => '每日出游1次',
    'use' => 15,
    'tasktype' => 53,
    'is_show' => 1,
    'icon' => 1,
  ),
  9 => 
  array (
    'id' => 9,
    'name' => '每日邀约',
    'name_cn' => '每日邀约次数',
    'awardexp' => 5,
    'type' => 1,
    'need' => 1,
    'info' => '每日邀约1次',
    'info_cn' => '每日邀约1次',
    'use' => 15,
    'tasktype' => 152,
    'is_show' => 1,
    'icon' => 1,
  ),
  10 => 
  array (
    'id' => 10,
    'name' => '每日廷斗',
    'name_cn' => '每日廷斗次数',
    'awardexp' => 5,
    'type' => 1,
    'need' => 1,
    'info' => '每日廷斗1次',
    'info_cn' => '每日廷斗1次',
    'use' => 5,
    'tasktype' => 122,
    'is_show' => 1,
    'icon' => 1,
  ),
  11 => 
  array (
    'id' => 11,
    'name' => '每日学习',
    'name_cn' => '每日伙伴才学学习1次',
    'awardexp' => 5,
    'type' => 1,
    'need' => 1,
    'info' => '每日伙伴才学学习1次',
    'info_cn' => '每日伙伴才学学习1次',
    'use' => 28,
    'tasktype' => 30,
    'is_show' => 1,
    'icon' => 1,
  ),
  12 => 
  array (
    'id' => 12,
    'name' => '偶尔看看',
    'name_cn' => '偶尔看看',
    'awardexp' => 25,
    'type' => 2,
    'need' => 5,
    'info' => '累积登陆天数',
    'info_cn' => '累积登陆天数',
    'use' => NULL,
    'tasktype' => 124,
    'is_show' => 1,
    'icon' => 1,
  ),
  13 => 
  array (
    'id' => 13,
    'name' => '日复一日',
    'name_cn' => '日复一日',
    'awardexp' => 50,
    'type' => 2,
    'need' => 10,
    'info' => '累积登陆天数',
    'info_cn' => '累积登陆天数',
    'use' => NULL,
    'tasktype' => 124,
    'is_show' => 1,
    'icon' => 1,
  ),
  14 => 
  array (
    'id' => 14,
    'name' => '坚持不懈',
    'name_cn' => '坚持不懈',
    'awardexp' => 125,
    'type' => 2,
    'need' => 15,
    'info' => '累积登陆天数',
    'info_cn' => '累积登陆天数',
    'use' => NULL,
    'tasktype' => 124,
    'is_show' => 1,
    'icon' => 1,
  ),
  15 => 
  array (
    'id' => 15,
    'name' => '持之以恒',
    'name_cn' => '持之以恒',
    'awardexp' => 300,
    'type' => 2,
    'need' => 20,
    'info' => '累积登陆天数',
    'info_cn' => '累积登陆天数',
    'use' => NULL,
    'tasktype' => 124,
    'is_show' => 1,
    'icon' => 1,
  ),
  16 => 
  array (
    'id' => 16,
    'name' => '水滴石穿',
    'name_cn' => '水滴石穿',
    'awardexp' => 500,
    'type' => 2,
    'need' => 25,
    'info' => '累积登陆天数',
    'info_cn' => '累积登陆天数',
    'use' => NULL,
    'tasktype' => 124,
    'is_show' => 1,
    'icon' => 1,
  ),
);