<?php
//VIP2表
return array (
  0 => 
  array (
    'vip' => 0,
    'is_cook' => 0,
    'is_study' => 0,
    'is_apprentice' => 0,
    'is_return' => 0,
    'is_fincook' => 0,
    'is_finstudy' => 0,
    'haoyou_num' => 10,
    'ban_num' => 5,
    'apply_num' => 10,
  ),
  1 => 
  array (
    'vip' => 1,
    'is_cook' => 0,
    'is_study' => 0,
    'is_apprentice' => 0,
    'is_return' => 0,
    'is_fincook' => 0,
    'is_finstudy' => 0,
    'haoyou_num' => 12,
    'ban_num' => 6,
    'apply_num' => 10,
  ),
  2 => 
  array (
    'vip' => 2,
    'is_cook' => 0,
    'is_study' => 0,
    'is_apprentice' => 0,
    'is_return' => 0,
    'is_fincook' => 0,
    'is_finstudy' => 0,
    'haoyou_num' => 14,
    'ban_num' => 7,
    'apply_num' => 10,
  ),
  3 => 
  array (
    'vip' => 3,
    'is_cook' => 0,
    'is_study' => 0,
    'is_apprentice' => 0,
    'is_return' => 0,
    'is_fincook' => 0,
    'is_finstudy' => 0,
    'haoyou_num' => 16,
    'ban_num' => 8,
    'apply_num' => 10,
  ),
  4 => 
  array (
    'vip' => 4,
    'is_cook' => 0,
    'is_study' => 0,
    'is_apprentice' => 0,
    'is_return' => 1,
    'is_fincook' => 0,
    'is_finstudy' => 1,
    'haoyou_num' => 18,
    'ban_num' => 9,
    'apply_num' => 10,
  ),
  5 => 
  array (
    'vip' => 5,
    'is_cook' => 0,
    'is_study' => 1,
    'is_apprentice' => 1,
    'is_return' => 1,
    'is_fincook' => 0,
    'is_finstudy' => 1,
    'haoyou_num' => 20,
    'ban_num' => 10,
    'apply_num' => 15,
  ),
  6 => 
  array (
    'vip' => 6,
    'is_cook' => 0,
    'is_study' => 1,
    'is_apprentice' => 1,
    'is_return' => 1,
    'is_fincook' => 0,
    'is_finstudy' => 1,
    'haoyou_num' => 22,
    'ban_num' => 11,
    'apply_num' => 15,
  ),
  7 => 
  array (
    'vip' => 7,
    'is_cook' => 0,
    'is_study' => 1,
    'is_apprentice' => 1,
    'is_return' => 1,
    'is_fincook' => 0,
    'is_finstudy' => 1,
    'haoyou_num' => 24,
    'ban_num' => 12,
    'apply_num' => 15,
  ),
  8 => 
  array (
    'vip' => 8,
    'is_cook' => 0,
    'is_study' => 1,
    'is_apprentice' => 1,
    'is_return' => 1,
    'is_fincook' => 0,
    'is_finstudy' => 1,
    'haoyou_num' => 26,
    'ban_num' => 13,
    'apply_num' => 20,
  ),
  9 => 
  array (
    'vip' => 9,
    'is_cook' => 0,
    'is_study' => 1,
    'is_apprentice' => 1,
    'is_return' => 1,
    'is_fincook' => 0,
    'is_finstudy' => 1,
    'haoyou_num' => 28,
    'ban_num' => 14,
    'apply_num' => 20,
  ),
  10 => 
  array (
    'vip' => 10,
    'is_cook' => 0,
    'is_study' => 1,
    'is_apprentice' => 1,
    'is_return' => 1,
    'is_fincook' => 0,
    'is_finstudy' => 1,
    'haoyou_num' => 30,
    'ban_num' => 15,
    'apply_num' => 20,
  ),
);