<?php
//寻访-事件（客户端）
return array (
  10000 => 
  array (
    'id' => 10000,
    'type' => 5,
    'object' => 220,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '你为调查布料碎片的线索，和蔺晟安出宫调查',
    'beizhu' => 442,
  ),
  10010 => 
  array (
    'id' => 10010,
    'type' => 5,
    'object' => 275,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '寄信人身份未明，你拿着信纸，出宫寻找线索',
    'beizhu' => NULL,
  ),
  10020 => 
  array (
    'id' => 10020,
    'type' => 5,
    'object' => 482,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 2,
    'group' => 0,
    'text' => '为了安葬满叔，你回到了从前的老宅附近',
    'beizhu' => NULL,
  ),
  10030 => 
  array (
    'id' => 10030,
    'type' => 5,
    'object' => 504,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 1,
    'group' => 0,
    'text' => '你来到了破庙，却发现一个熟悉的身影……',
    'beizhu' => NULL,
  ),
  10060 => 
  array (
    'id' => 10060,
    'type' => 5,
    'object' => 802,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 3,
    'group' => 0,
    'text' => '你出宫采买，路过一家肉铺，恰好看到屠户剔肉',
    'beizhu' => NULL,
  ),
  10140 => 
  array (
    'id' => 10140,
    'type' => 5,
    'object' => 1060,
    'prob' => 0,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 2,
    'group' => 0,
    'text' => '这些天的事情终于告一段落，你难得空闲，出城散心',
    'beizhu' => NULL,
  ),
  100 => 
  array (
    'id' => 100,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_1108',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  150 => 
  array (
    'id' => 150,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_1208',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  155 => 
  array (
    'id' => 155,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_1308',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  160 => 
  array (
    'id' => 160,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_1408',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  165 => 
  array (
    'id' => 165,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_1508',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  170 => 
  array (
    'id' => 170,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_1608',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  200 => 
  array (
    'id' => 200,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_2006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  300 => 
  array (
    'id' => 300,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 2,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  310 => 
  array (
    'id' => 310,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 3,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  320 => 
  array (
    'id' => 320,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 4,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  330 => 
  array (
    'id' => 330,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  340 => 
  array (
    'id' => 340,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  350 => 
  array (
    'id' => 350,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 8,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  360 => 
  array (
    'id' => 360,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 10,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  370 => 
  array (
    'id' => 370,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 14,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  380 => 
  array (
    'id' => 380,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 16,
    'group' => 'xunfang_3006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  400 => 
  array (
    'id' => 400,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_4106',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  410 => 
  array (
    'id' => 410,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_4206',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  420 => 
  array (
    'id' => 420,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_4306',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  430 => 
  array (
    'id' => 430,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_4406',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  440 => 
  array (
    'id' => 440,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_4506',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  450 => 
  array (
    'id' => 450,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_4606',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  500 => 
  array (
    'id' => 500,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 4,
    'group' => 'xunfang_5006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  510 => 
  array (
    'id' => 510,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_5006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  520 => 
  array (
    'id' => 520,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 8,
    'group' => 'xunfang_5006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  530 => 
  array (
    'id' => 530,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 12,
    'group' => 'xunfang_5006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  540 => 
  array (
    'id' => 540,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_5006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  550 => 
  array (
    'id' => 550,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 17,
    'group' => 'xunfang_5006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  560 => 
  array (
    'id' => 560,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 18,
    'group' => 'xunfang_5006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  600 => 
  array (
    'id' => 600,
    'type' => 1,
    'object' => 0,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 0,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_6006',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  700 => 
  array (
    'id' => 700,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_7106',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  710 => 
  array (
    'id' => 710,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_7206',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  720 => 
  array (
    'id' => 720,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_7306',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  730 => 
  array (
    'id' => 730,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_7406',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  740 => 
  array (
    'id' => 740,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_7506',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  750 => 
  array (
    'id' => 750,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_7606',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  800 => 
  array (
    'id' => 800,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_8110',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  810 => 
  array (
    'id' => 810,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_8210',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  820 => 
  array (
    'id' => 820,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_8310',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  830 => 
  array (
    'id' => 830,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_8410',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  840 => 
  array (
    'id' => 840,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_8510',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  850 => 
  array (
    'id' => 850,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 1,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 0,
    'group' => 'xunfang_8610',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  900 => 
  array (
    'id' => 900,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 'xunfang_9108',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  910 => 
  array (
    'id' => 910,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 'xunfang_9208',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  920 => 
  array (
    'id' => 920,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 'xunfang_9308',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  930 => 
  array (
    'id' => 930,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 'xunfang_9408',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  940 => 
  array (
    'id' => 940,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 'xunfang_9508',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  950 => 
  array (
    'id' => 950,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 5,
    'group' => 'xunfang_9608',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  901 => 
  array (
    'id' => 901,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 'xunfang_9108',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  911 => 
  array (
    'id' => 911,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 'xunfang_9208',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  921 => 
  array (
    'id' => 921,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 'xunfang_9308',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  931 => 
  array (
    'id' => 931,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 'xunfang_9408',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  941 => 
  array (
    'id' => 941,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 'xunfang_9508',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  951 => 
  array (
    'id' => 951,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 9,
    'group' => 'xunfang_9608',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  902 => 
  array (
    'id' => 902,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 11,
    'group' => 'xunfang_9108',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  912 => 
  array (
    'id' => 912,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 11,
    'group' => 'xunfang_9208',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  922 => 
  array (
    'id' => 922,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 11,
    'group' => 'xunfang_9308',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  932 => 
  array (
    'id' => 932,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 11,
    'group' => 'xunfang_9408',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  942 => 
  array (
    'id' => 942,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 11,
    'group' => 'xunfang_9508',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  952 => 
  array (
    'id' => 952,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 11,
    'group' => 'xunfang_9608',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  903 => 
  array (
    'id' => 903,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_9108',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  913 => 
  array (
    'id' => 913,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_9208',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  923 => 
  array (
    'id' => 923,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_9308',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  933 => 
  array (
    'id' => 933,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_9408',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  943 => 
  array (
    'id' => 943,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_9508',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  953 => 
  array (
    'id' => 953,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_9608',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1000 => 
  array (
    'id' => 1000,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_10106',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1010 => 
  array (
    'id' => 1010,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_10206',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1020 => 
  array (
    'id' => 1020,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_10306',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1030 => 
  array (
    'id' => 1030,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_10406',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1040 => 
  array (
    'id' => 1040,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_10506',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1050 => 
  array (
    'id' => 1050,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 6,
    'group' => 'xunfang_10606',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1001 => 
  array (
    'id' => 1001,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 'xunfang_10106',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1011 => 
  array (
    'id' => 1011,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 'xunfang_10206',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1021 => 
  array (
    'id' => 1021,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 'xunfang_10306',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1031 => 
  array (
    'id' => 1031,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 'xunfang_10406',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1041 => 
  array (
    'id' => 1041,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 'xunfang_10506',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1051 => 
  array (
    'id' => 1051,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 7,
    'group' => 'xunfang_10606',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1002 => 
  array (
    'id' => 1002,
    'type' => 1,
    'object' => 1,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_10106',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1012 => 
  array (
    'id' => 1012,
    'type' => 1,
    'object' => 2,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_10206',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1022 => 
  array (
    'id' => 1022,
    'type' => 1,
    'object' => 3,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_10306',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1032 => 
  array (
    'id' => 1032,
    'type' => 1,
    'object' => 4,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_10406',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1042 => 
  array (
    'id' => 1042,
    'type' => 1,
    'object' => 5,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_10506',
    'text' => NULL,
    'beizhu' => NULL,
  ),
  1052 => 
  array (
    'id' => 1052,
    'type' => 1,
    'object' => 6,
    'prob' => 100,
    'shili' => 0,
    'jibang' => 20,
    'qiyun' => 0,
    'ep' => 0,
    'locale' => 13,
    'group' => 'xunfang_10606',
    'text' => NULL,
    'beizhu' => NULL,
  ),
);